kind: pipeline
name: flatsharing

steps:
- name: go-deps
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make dep

- name: test
  group: test-lint-coverage
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make test

- name: lint
  group: test-lint-coverage
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make lint

- name: coverage
  group: test-lint-coverage
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make coverage

- name: protoc
  group: build
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make protoc

- name: build-api-auth
  group: build
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make build-api-auth

- name: build-api-flatsharing
  group: build
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make build-api-flatsharing

- name: build-support
  group: build
  pull: true
  image: flatsharing/workflow:latest
  working_dir: /code
  volumes:
  - name: cache
    path: /go
  commands:
    - make build-support

- name: docker-api-auth
  group: docker
  image: plugins/docker
  settings:
    tags: latest
    repo: flatsharing/api-auth
    dockerfile: build/docker/api-auth.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: master
    event: push
    status: success

- name: docker-api-flatsharing
  group: docker
  image: plugins/docker
  settings:
    tags: latest
    repo: flatsharing/api-flatsharing
    dockerfile: build/docker/api-flatsharing.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: master
    event: push
    status: success

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token: e897d4e0-b3ff-4c5d-91e6-2d3ff15a9ee6

volumes:
- name: cache
  temp: {}
