kind: pipeline
name: flatsharing

steps:
- name: go-deps
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make dep

- name: test
  group: test-lint-coverage
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make test

- name: lint
  group: test-lint-coverage
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make lint

- name: coverage
  group: test-lint-coverage
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make coverage

- name: protoc
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make dep
    - make protoc

- name: build-auth
  group: build
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make build-auth

- name: build-flatsharing
  group: build
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make build-flatsharing

- name: build-support
  group: build
  image: flatsharing/workflow:latest
  pull: true
  commands:
    - make build-support

- name: docker-auth
  group: docker
  image: plugins/docker
  settings:
    tags: latest
    repo: flatsharing/auth
    dockerfile: auth.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: master
    event: push
    status: success

- name: docker-fs_service
  group: docker
  image: plugins/docker
  settings:
    tags: latest
    repo: flatsharing/fs_service
    dockerfile: fs_service.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: master
    event: push
    status: success

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token: e897d4e0-b3ff-4c5d-91e6-2d3ff15a9ee6
