workspace:
  base: /go

pipeline:
  app:
    image: golang:${GO_VERSION}
    commands:
      - export GOPATH=$$(pwd)
      - export PATH=$$PATH":$$GOPATH/bin"
      - make dep
      - make lint
      - make test
      - make build

  codecov:
    image: robertstettner/drone-codecov
    token: e897d4e0-b3ff-4c5d-91e6-2d3ff15a9ee6

matrix:
  GO_VERSION:
    - latest
    - 1.9
    - 1.8
