workspace:
  base: /go

pipeline:
  all:
    image: golang:latest
    commands:
      - export GOPATH=$$(pwd)
      - export PATH=$$PATH":$$GOPATH/bin"
      - make dep
      - make lint
      - make test
      - make build
