workspace:
  base: /go

pipeline:
  go-deps:
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make dep

  test:
    group: test-lint-coverage
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make test

  lint:
    group: test-lint-coverage
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make lint

  coverage:
    group: test-lint-coverage
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make coverage

  protoc:
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make protoc

  build-auth:
    group: build
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make build-auth

  build-flatsharing:
    group: build
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make build-flatsharing

  build-support:
    group: build
    image: flatsharing/workflow:latest
    pull: true
    commands:
      - make build-support

  docker-auth:
    group: docker
    image: plugins/docker
    tags: latest
    repo: flatsharing/auth
    dockerfile: auth.Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
      status: success

  docker-fs_service:
    group: docker
    image: plugins/docker
    tags: latest
    repo: flatsharing/fs_service
    dockerfile: fs_service.Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
      status: success

  codecov:
    image: robertstettner/drone-codecov
    token: e897d4e0-b3ff-4c5d-91e6-2d3ff15a9ee6
