workspace:
  base: /go

pipeline:
  app:
    image: golang:${GO_VERSION}
    commands:
      - apt update && apt install -y bsdtar
      - export GO111MODULE=on
      - export PATH=$$PATH":$$GOPATH/bin"
      - make dep
      - make lint
      - make test
      - make coverage
      - make build-auth
      - make build-support

  codecov:
    image: robertstettner/drone-codecov
    token: e897d4e0-b3ff-4c5d-91e6-2d3ff15a9ee6

matrix:
  GO_VERSION:
    - 1.11
