version: '3'
services:
  mongo:
    image: mongo:3.7-jessie
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=611bukBNpbA3
    - MONGO_INITDB_DATABASE=flatsharing
    ports:
    - "27017:27017"
    command: --bind_ip 0.0.0.0
    volumes:
    - ./data:/data/db
    labels:
      NAME: "mongo"
  mongo-express:
    image: mongo-express:latest
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=611bukBNpbA3
    ports:
    - "8081:8081"
    links:
    - mongo:mongo
    labels:
      NAME: "mongo-express"
