version: '3.7'

services:
  workspace:
    image: flatsharing/workflow:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./:/code/
    command: sleep infinity

  auth:
    image: itsalex/alpine-reflex:latest
    restart: unless-stopped
    environment:
      - FS_AUTH_GRPC_LISTEN_ADDR=0.0.0.0
      - FS_AUTH_GRPC_LISTEN_PORT=8080
      - FS_AUTH_JSON_LISTEN_ADDR=0.0.0.0
      - FS_AUTH_JSON_LISTEN_PORT=8081
      - FS_AUTH_PSQL_HOST=postgres
      - FS_AUTH_PSQL_PORT=5432
      - FS_AUTH_PSQL_USER=flatsharing
      - FS_AUTH_PSQL_PASSWORD=password
      - FS_AUTH_PSQL_DBNAME=flatsharing
      - FS_AUTH_PSQL_SSLMODE=disable
    volumes:
      - ./:/code/
    ports:
      - 8080:8080
      - 8081:8081
    command: reflex -g code/assets/bin/auth-server -s /code/assets/bin/auth-server

  flatsharing:
    image: itsalex/alpine-reflex:latest
    restart: unless-stopped
    environment:
      - FS_SERVICE_GRPC_LISTEN_ADDR=0.0.0.0
      - FS_SERVICE_GRPC_LISTEN_PORT=8082
      - FS_SERVICE_JSON_LISTEN_ADDR=0.0.0.0
      - FS_SERVICE_JSON_LISTEN_PORT=8083
      - FS_SERVICE_PSQL_HOST=postgres
      - FS_SERVICE_PSQL_PORT=5432
      - FS_SERVICE_PSQL_USER=flatsharing
      - FS_SERVICE_PSQL_PASSWORD=password
      - FS_SERVICE_PSQL_DBNAME=flatsharing
      - FS_SERVICE_PSQL_SSLMODE=disable
    volumes:
      - ./:/code/
    ports:
      - 8082:8082
      - 8083:8083
    command: reflex -g code/assets/bin/flatsharing-server -s /code/assets/bin/flatsharing-server

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=flatsharing
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flatsharing
      - DB_EXTENSION=uuid-ossp
    volumes:
      - ./assets/postgres/data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  wait_postgres:
    image: "waisbrot/wait"
    environment:
      TARGETS: postgres:5432

