version: '3.5'
services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=flatsharing
      - POSTGRES_PASSWORD=611bukBNpbA3
      - POSTGRES_DB=flatsharing
      - DB_EXTENSION=uuid-ossp
      - DEBUG=true
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  wait_postgres:
    image: "waisbrot/wait"
    environment:
      TARGETS: postgres:5432
