version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
    - POSTGRES_USER=flatsharing
    - POSTGRES_PASSWORD=611bukBNpbA3
    - POSTGRES_DB=flatsharing
    - DB_EXTENSION=uuid-ossp
    - DEBUG=true
    volumes:
    - ./data/:/var/lib/postgresql/data
    ports:
    - "5432:5432"
