// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package v1 // import "src/auth/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{0}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{1}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SigninRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninRequest) Reset()         { *m = SigninRequest{} }
func (m *SigninRequest) String() string { return proto.CompactTextString(m) }
func (*SigninRequest) ProtoMessage()    {}
func (*SigninRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{2}
}
func (m *SigninRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninRequest.Unmarshal(m, b)
}
func (m *SigninRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninRequest.Marshal(b, m, deterministic)
}
func (dst *SigninRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninRequest.Merge(dst, src)
}
func (m *SigninRequest) XXX_Size() int {
	return xxx_messageInfo_SigninRequest.Size(m)
}
func (m *SigninRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SigninRequest proto.InternalMessageInfo

func (m *SigninRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *SigninRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SigninResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninResponse) Reset()         { *m = SigninResponse{} }
func (m *SigninResponse) String() string { return proto.CompactTextString(m) }
func (*SigninResponse) ProtoMessage()    {}
func (*SigninResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{3}
}
func (m *SigninResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninResponse.Unmarshal(m, b)
}
func (m *SigninResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninResponse.Marshal(b, m, deterministic)
}
func (dst *SigninResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninResponse.Merge(dst, src)
}
func (m *SigninResponse) XXX_Size() int {
	return xxx_messageInfo_SigninResponse.Size(m)
}
func (m *SigninResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SigninResponse proto.InternalMessageInfo

func (m *SigninResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ListUsersRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{4}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListUsersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListUsersResponse struct {
	// See https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/monitoring/apiv3/metric_client.go#L137
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalPageSize        int32    `protobuf:"varint,3,opt,name=total_page_size,json=totalPageSize,proto3" json:"total_page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{5}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListUsersResponse) GetTotalPageSize() int32 {
	if m != nil {
		return m.TotalPageSize
	}
	return 0
}

type GetUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{6}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{7}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	// or here https://github.com/gogo/grpc-example/commit/6c217371b67a89609c632f047477fa5a1123ac93
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{8}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{9}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mail                 string   `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Login                string   `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Firstname            string   `protobuf:"bytes,5,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,6,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Role                 int32    `protobuf:"varint,8,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_392dd30882c615f8, []int{10}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "flatsharing.auth.v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "flatsharing.auth.v1.CreateUserResponse")
	proto.RegisterType((*SigninRequest)(nil), "flatsharing.auth.v1.SigninRequest")
	proto.RegisterType((*SigninResponse)(nil), "flatsharing.auth.v1.SigninResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "flatsharing.auth.v1.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "flatsharing.auth.v1.ListUsersResponse")
	proto.RegisterType((*GetUserRequest)(nil), "flatsharing.auth.v1.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "flatsharing.auth.v1.GetUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "flatsharing.auth.v1.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "flatsharing.auth.v1.DeleteUserRequest")
	proto.RegisterType((*User)(nil), "flatsharing.auth.v1.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServicesClient is the client API for AuthServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServicesClient interface {
	Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type authServicesClient struct {
	cc *grpc.ClientConn
}

func NewAuthServicesClient(cc *grpc.ClientConn) AuthServicesClient {
	return &authServicesClient{cc}
}

func (c *authServicesClient) Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninResponse, error) {
	out := new(SigninResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.auth.v1.AuthServices/Signin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServicesClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.auth.v1.AuthServices/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServicesClient) GetUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.auth.v1.AuthServices/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServicesClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.auth.v1.AuthServices/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServicesClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.auth.v1.AuthServices/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServicesClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.auth.v1.AuthServices/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServicesServer is the server API for AuthServices service.
type AuthServicesServer interface {
	Signin(context.Context, *SigninRequest) (*SigninResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*empty.Empty, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*empty.Empty, error)
}

func RegisterAuthServicesServer(s *grpc.Server, srv AuthServicesServer) {
	s.RegisterService(&_AuthServices_serviceDesc, srv)
}

func _AuthServices_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigninRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServicesServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.auth.v1.AuthServices/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServicesServer).Signin(ctx, req.(*SigninRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthServices_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServicesServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.auth.v1.AuthServices/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServicesServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthServices_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServicesServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.auth.v1.AuthServices/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServicesServer).GetUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthServices_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServicesServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.auth.v1.AuthServices/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServicesServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthServices_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServicesServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.auth.v1.AuthServices/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServicesServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthServices_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServicesServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.auth.v1.AuthServices/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServicesServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flatsharing.auth.v1.AuthServices",
	HandlerType: (*AuthServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signin",
			Handler:    _AuthServices_Signin_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AuthServices_CreateUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _AuthServices_GetUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthServices_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _AuthServices_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _AuthServices_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_392dd30882c615f8) }

var fileDescriptor_auth_392dd30882c615f8 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x86, 0xd5, 0xae, 0xdd, 0xda, 0xaf, 0x74, 0x3f, 0xde, 0x80, 0x92, 0x6d, 0xd2, 0x14, 0x46,
	0x41, 0x93, 0x48, 0xb4, 0x71, 0x06, 0x07, 0xb0, 0xf1, 0x77, 0x02, 0x68, 0xea, 0xd8, 0x09, 0x27,
	0x95, 0xb7, 0xb8, 0xa9, 0xd5, 0x34, 0x09, 0xb1, 0x5b, 0x60, 0x08, 0x21, 0x71, 0x0b, 0x70, 0x05,
	0xdc, 0x12, 0xb7, 0x00, 0xf7, 0x81, 0xfc, 0xd9, 0x49, 0xd7, 0x35, 0xed, 0x40, 0x3b, 0xa9, 0x62,
	0xfb, 0xf5, 0xfb, 0xf8, 0xe7, 0xfd, 0x5c, 0x00, 0x3a, 0x90, 0x5d, 0x27, 0x4e, 0x22, 0x19, 0x91,
	0xd5, 0x4e, 0x40, 0xa5, 0xe8, 0xd2, 0x84, 0x87, 0xbe, 0x83, 0xfd, 0xc3, 0x5d, 0x6b, 0xdd, 0x8f,
	0x22, 0x3f, 0x60, 0x2e, 0x4a, 0x4e, 0x06, 0x1d, 0x97, 0xf5, 0x63, 0xf9, 0x49, 0xcf, 0xb0, 0xb6,
	0x2e, 0x0e, 0x76, 0x38, 0x0b, 0xbc, 0x76, 0x9f, 0x8a, 0x9e, 0x51, 0x6c, 0x18, 0x05, 0x8d, 0xb9,
	0x4b, 0xc3, 0x30, 0x92, 0x54, 0xf2, 0x28, 0x14, 0x7a, 0xd4, 0x3e, 0x80, 0x95, 0xa7, 0x09, 0xa3,
	0x92, 0x1d, 0x0b, 0x96, 0xb4, 0xd8, 0xfb, 0x01, 0x13, 0x92, 0xdc, 0x87, 0xd2, 0x40, 0xb0, 0xa4,
	0x51, 0xd8, 0x2a, 0xdc, 0xab, 0xed, 0xdd, 0x72, 0x72, 0x56, 0xe5, 0xa0, 0x1e, 0x65, 0xf6, 0x36,
	0x90, 0xf3, 0x1e, 0x22, 0x8e, 0x42, 0xc1, 0xc8, 0x22, 0x14, 0xb9, 0x87, 0x16, 0xd5, 0x56, 0x91,
	0x7b, 0xf6, 0x3e, 0xd4, 0x8f, 0xb8, 0x1f, 0xf2, 0x30, 0xa5, 0xac, 0x41, 0x39, 0x88, 0x7c, 0x1e,
	0x1a, 0x8d, 0x6e, 0x10, 0x0b, 0x2a, 0x31, 0x15, 0xe2, 0x43, 0x94, 0x78, 0x8d, 0x22, 0x0e, 0x64,
	0x6d, 0xbb, 0x09, 0x8b, 0xa9, 0x85, 0x81, 0xac, 0x41, 0x59, 0x46, 0x3d, 0x96, 0x79, 0x60, 0xc3,
	0x7e, 0x03, 0xcb, 0xaf, 0xb8, 0x90, 0x6a, 0x39, 0x22, 0xa5, 0xad, 0x43, 0x35, 0xa6, 0x3e, 0x6b,
	0x0b, 0x7e, 0xc6, 0x50, 0x5d, 0x56, 0xc6, 0x3e, 0x3b, 0xe2, 0x67, 0x8c, 0x6c, 0x02, 0xe0, 0xa0,
	0xf6, 0xd2, 0x58, 0x94, 0xbf, 0x45, 0xbf, 0x1f, 0x05, 0x58, 0x39, 0x67, 0x68, 0xd8, 0x2e, 0x94,
	0xd5, 0xf6, 0x45, 0xa3, 0xb0, 0x35, 0x37, 0xfb, 0x98, 0xb4, 0x8e, 0x34, 0x61, 0x29, 0x64, 0x1f,
	0x65, 0x7b, 0x02, 0x55, 0x57, 0xdd, 0x87, 0x29, 0x4e, 0xe9, 0x64, 0x24, 0x69, 0xd0, 0x1e, 0x2d,
	0x78, 0x0e, 0x17, 0x5c, 0xc7, 0xee, 0x43, 0xb3, 0x6a, 0xfb, 0x31, 0x2c, 0xbe, 0x64, 0xf2, 0x0a,
	0x17, 0xf7, 0x04, 0x96, 0x32, 0x03, 0xb3, 0xa9, 0xff, 0x74, 0xf8, 0x0a, 0x2b, 0xc7, 0xb1, 0x37,
	0x25, 0x3e, 0xc5, 0x7f, 0xf2, 0x20, 0x8f, 0xa0, 0x36, 0x40, 0x0f, 0x4c, 0x2d, 0x6e, 0xb5, 0xb6,
	0x67, 0x39, 0x3a, 0xb6, 0x4e, 0x1a, 0x6c, 0xe7, 0x85, 0x0a, 0xf6, 0x6b, 0x2a, 0x7a, 0x2d, 0xd0,
	0x72, 0xf5, 0xad, 0xf2, 0xfb, 0x8c, 0x05, 0xec, 0x4a, 0xf9, 0xfd, 0x53, 0x80, 0x92, 0x6a, 0x5e,
	0x8c, 0x2c, 0x21, 0x50, 0xea, 0x53, 0x1e, 0x98, 0x5b, 0xc2, 0x6f, 0x95, 0x4f, 0x35, 0x29, 0xa4,
	0x7d, 0x7d, 0x2b, 0xd5, 0x56, 0xd6, 0x1e, 0x25, 0xba, 0x74, 0x3e, 0xd1, 0x1b, 0x50, 0xed, 0xf0,
	0x44, 0x48, 0x9c, 0x52, 0xd6, 0xd9, 0xca, 0x3a, 0x94, 0x5f, 0x40, 0xcd, 0xe0, 0xbc, 0xf6, 0x4b,
	0xdb, 0x63, 0xb5, 0xb0, 0x30, 0x5e, 0x0b, 0x6a, 0x6d, 0x49, 0x14, 0xb0, 0x46, 0x05, 0x93, 0x81,
	0xdf, 0x2a, 0xc6, 0xa7, 0x58, 0x88, 0x5e, 0x9b, 0xca, 0x46, 0x55, 0xa3, 0x4c, 0xcf, 0xbe, 0xdc,
	0xfb, 0x59, 0x86, 0x6b, 0xfb, 0x03, 0xd9, 0x3d, 0x62, 0xc9, 0x90, 0x9f, 0x32, 0x41, 0xba, 0x30,
	0xaf, 0xeb, 0x89, 0xd8, 0xb9, 0x67, 0x34, 0x56, 0xaf, 0xd6, 0xed, 0x99, 0x1a, 0x9d, 0x1f, 0xfb,
	0xfa, 0xb7, 0x5f, 0xbf, 0xbf, 0x17, 0x97, 0x6c, 0x70, 0x87, 0xbb, 0xae, 0xc0, 0xb1, 0x87, 0x85,
	0x1d, 0x92, 0x00, 0x8c, 0x9e, 0x08, 0xd2, 0xcc, 0x75, 0x9a, 0x78, 0x87, 0xac, 0xbb, 0x97, 0xea,
	0x0c, 0x75, 0x15, 0xa9, 0x75, 0xbb, 0xa2, 0xa8, 0xea, 0x3a, 0x14, 0xb3, 0x07, 0x15, 0x93, 0x6e,
	0x41, 0xee, 0xe4, 0x3a, 0x5d, 0x7c, 0x24, 0xac, 0xe6, 0x65, 0x32, 0xc3, 0x5b, 0x46, 0x1e, 0x90,
	0x8c, 0x47, 0x62, 0x58, 0x30, 0x30, 0x92, 0x7f, 0x4e, 0xe3, 0x95, 0x6a, 0x6d, 0xcf, 0x16, 0x19,
	0x8e, 0x85, 0x9c, 0x35, 0x42, 0x52, 0x8e, 0xfb, 0x59, 0xfd, 0x3a, 0xdc, 0xfb, 0x42, 0x7a, 0x00,
	0xa3, 0xd2, 0x9b, 0x72, 0xa4, 0x13, 0xb5, 0x69, 0xdd, 0x98, 0xa8, 0xab, 0xe7, 0xea, 0xdf, 0xc4,
	0xde, 0x44, 0xd2, 0x4d, 0x2b, 0x87, 0xa4, 0xce, 0xb2, 0x0b, 0x30, 0x2a, 0xb3, 0x29, 0xb0, 0x89,
	0x3a, 0x9c, 0x0a, 0x33, 0xdb, 0xda, 0xc9, 0x81, 0x1d, 0xd4, 0xdf, 0xd5, 0x44, 0x72, 0xea, 0x2a,
	0x53, 0x77, 0xb8, 0x7b, 0x32, 0x8f, 0x53, 0x1f, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xd1,
	0x74, 0xd7, 0x26, 0x07, 0x00, 0x00,
}
