// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flatsharing.proto

package v1 // import "internal/flatsharing/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListFlatsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFlatsRequest) Reset()         { *m = ListFlatsRequest{} }
func (m *ListFlatsRequest) String() string { return proto.CompactTextString(m) }
func (*ListFlatsRequest) ProtoMessage()    {}
func (*ListFlatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{0}
}
func (m *ListFlatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFlatsRequest.Unmarshal(m, b)
}
func (m *ListFlatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFlatsRequest.Marshal(b, m, deterministic)
}
func (dst *ListFlatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFlatsRequest.Merge(dst, src)
}
func (m *ListFlatsRequest) XXX_Size() int {
	return xxx_messageInfo_ListFlatsRequest.Size(m)
}
func (m *ListFlatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFlatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFlatsRequest proto.InternalMessageInfo

func (m *ListFlatsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListFlatsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListFlatsResponse struct {
	// See https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/monitoring/apiv3/metric_client.go#L137
	Flat                 []*Flat  `protobuf:"bytes,1,rep,name=flat,proto3" json:"flat,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalPageSize        int32    `protobuf:"varint,3,opt,name=total_page_size,json=totalPageSize,proto3" json:"total_page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFlatsResponse) Reset()         { *m = ListFlatsResponse{} }
func (m *ListFlatsResponse) String() string { return proto.CompactTextString(m) }
func (*ListFlatsResponse) ProtoMessage()    {}
func (*ListFlatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{1}
}
func (m *ListFlatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFlatsResponse.Unmarshal(m, b)
}
func (m *ListFlatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFlatsResponse.Marshal(b, m, deterministic)
}
func (dst *ListFlatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFlatsResponse.Merge(dst, src)
}
func (m *ListFlatsResponse) XXX_Size() int {
	return xxx_messageInfo_ListFlatsResponse.Size(m)
}
func (m *ListFlatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFlatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFlatsResponse proto.InternalMessageInfo

func (m *ListFlatsResponse) GetFlat() []*Flat {
	if m != nil {
		return m.Flat
	}
	return nil
}

func (m *ListFlatsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListFlatsResponse) GetTotalPageSize() int32 {
	if m != nil {
		return m.TotalPageSize
	}
	return 0
}

type GetFlatRequest struct {
	Flat                 *Flat    `protobuf:"bytes,1,opt,name=flat,proto3" json:"flat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlatRequest) Reset()         { *m = GetFlatRequest{} }
func (m *GetFlatRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlatRequest) ProtoMessage()    {}
func (*GetFlatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{2}
}
func (m *GetFlatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlatRequest.Unmarshal(m, b)
}
func (m *GetFlatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlatRequest.Marshal(b, m, deterministic)
}
func (dst *GetFlatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlatRequest.Merge(dst, src)
}
func (m *GetFlatRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlatRequest.Size(m)
}
func (m *GetFlatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlatRequest proto.InternalMessageInfo

func (m *GetFlatRequest) GetFlat() *Flat {
	if m != nil {
		return m.Flat
	}
	return nil
}

type GetFlatResponse struct {
	Flat                 *Flat    `protobuf:"bytes,1,opt,name=flat,proto3" json:"flat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlatResponse) Reset()         { *m = GetFlatResponse{} }
func (m *GetFlatResponse) String() string { return proto.CompactTextString(m) }
func (*GetFlatResponse) ProtoMessage()    {}
func (*GetFlatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{3}
}
func (m *GetFlatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlatResponse.Unmarshal(m, b)
}
func (m *GetFlatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlatResponse.Marshal(b, m, deterministic)
}
func (dst *GetFlatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlatResponse.Merge(dst, src)
}
func (m *GetFlatResponse) XXX_Size() int {
	return xxx_messageInfo_GetFlatResponse.Size(m)
}
func (m *GetFlatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlatResponse proto.InternalMessageInfo

func (m *GetFlatResponse) GetFlat() *Flat {
	if m != nil {
		return m.Flat
	}
	return nil
}

type CreateFlatRequest struct {
	Flat                 *Flat    `protobuf:"bytes,1,opt,name=flat,proto3" json:"flat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFlatRequest) Reset()         { *m = CreateFlatRequest{} }
func (m *CreateFlatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFlatRequest) ProtoMessage()    {}
func (*CreateFlatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{4}
}
func (m *CreateFlatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFlatRequest.Unmarshal(m, b)
}
func (m *CreateFlatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFlatRequest.Marshal(b, m, deterministic)
}
func (dst *CreateFlatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFlatRequest.Merge(dst, src)
}
func (m *CreateFlatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFlatRequest.Size(m)
}
func (m *CreateFlatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFlatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFlatRequest proto.InternalMessageInfo

func (m *CreateFlatRequest) GetFlat() *Flat {
	if m != nil {
		return m.Flat
	}
	return nil
}

type CreateFlatResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFlatResponse) Reset()         { *m = CreateFlatResponse{} }
func (m *CreateFlatResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFlatResponse) ProtoMessage()    {}
func (*CreateFlatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{5}
}
func (m *CreateFlatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFlatResponse.Unmarshal(m, b)
}
func (m *CreateFlatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFlatResponse.Marshal(b, m, deterministic)
}
func (dst *CreateFlatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFlatResponse.Merge(dst, src)
}
func (m *CreateFlatResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFlatResponse.Size(m)
}
func (m *CreateFlatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFlatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFlatResponse proto.InternalMessageInfo

func (m *CreateFlatResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateFlatRequest struct {
	Flat *Flat `protobuf:"bytes,1,opt,name=flat,proto3" json:"flat,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	// or here https://github.com/gogo/grpc-example/commit/6c217371b67a89609c632f047477fa5a1123ac93
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateFlatRequest) Reset()         { *m = UpdateFlatRequest{} }
func (m *UpdateFlatRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFlatRequest) ProtoMessage()    {}
func (*UpdateFlatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{6}
}
func (m *UpdateFlatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFlatRequest.Unmarshal(m, b)
}
func (m *UpdateFlatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFlatRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateFlatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFlatRequest.Merge(dst, src)
}
func (m *UpdateFlatRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFlatRequest.Size(m)
}
func (m *UpdateFlatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFlatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFlatRequest proto.InternalMessageInfo

func (m *UpdateFlatRequest) GetFlat() *Flat {
	if m != nil {
		return m.Flat
	}
	return nil
}

func (m *UpdateFlatRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteFlatRequest struct {
	Flat                 *Flat    `protobuf:"bytes,1,opt,name=flat,proto3" json:"flat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFlatRequest) Reset()         { *m = DeleteFlatRequest{} }
func (m *DeleteFlatRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFlatRequest) ProtoMessage()    {}
func (*DeleteFlatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{7}
}
func (m *DeleteFlatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFlatRequest.Unmarshal(m, b)
}
func (m *DeleteFlatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFlatRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFlatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFlatRequest.Merge(dst, src)
}
func (m *DeleteFlatRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFlatRequest.Size(m)
}
func (m *DeleteFlatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFlatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFlatRequest proto.InternalMessageInfo

func (m *DeleteFlatRequest) GetFlat() *Flat {
	if m != nil {
		return m.Flat
	}
	return nil
}

type Flat struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flat) Reset()         { *m = Flat{} }
func (m *Flat) String() string { return proto.CompactTextString(m) }
func (*Flat) ProtoMessage()    {}
func (*Flat) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{8}
}
func (m *Flat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flat.Unmarshal(m, b)
}
func (m *Flat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flat.Marshal(b, m, deterministic)
}
func (dst *Flat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flat.Merge(dst, src)
}
func (m *Flat) XXX_Size() int {
	return xxx_messageInfo_Flat.Size(m)
}
func (m *Flat) XXX_DiscardUnknown() {
	xxx_messageInfo_Flat.DiscardUnknown(m)
}

var xxx_messageInfo_Flat proto.InternalMessageInfo

func (m *Flat) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Flat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Flat) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type ListPurchasesRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPurchasesRequest) Reset()         { *m = ListPurchasesRequest{} }
func (m *ListPurchasesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesRequest) ProtoMessage()    {}
func (*ListPurchasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{9}
}
func (m *ListPurchasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesRequest.Unmarshal(m, b)
}
func (m *ListPurchasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesRequest.Marshal(b, m, deterministic)
}
func (dst *ListPurchasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesRequest.Merge(dst, src)
}
func (m *ListPurchasesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesRequest.Size(m)
}
func (m *ListPurchasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesRequest proto.InternalMessageInfo

func (m *ListPurchasesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPurchasesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListPurchasesResponse struct {
	// See https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/monitoring/apiv3/metric_client.go#L137
	Purchase             []*Purchase `protobuf:"bytes,1,rep,name=purchase,proto3" json:"purchase,omitempty"`
	NextPageToken        string      `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalPageSize        int32       `protobuf:"varint,3,opt,name=total_page_size,json=totalPageSize,proto3" json:"total_page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPurchasesResponse) Reset()         { *m = ListPurchasesResponse{} }
func (m *ListPurchasesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesResponse) ProtoMessage()    {}
func (*ListPurchasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{10}
}
func (m *ListPurchasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesResponse.Unmarshal(m, b)
}
func (m *ListPurchasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesResponse.Marshal(b, m, deterministic)
}
func (dst *ListPurchasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesResponse.Merge(dst, src)
}
func (m *ListPurchasesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesResponse.Size(m)
}
func (m *ListPurchasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesResponse proto.InternalMessageInfo

func (m *ListPurchasesResponse) GetPurchase() []*Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

func (m *ListPurchasesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListPurchasesResponse) GetTotalPageSize() int32 {
	if m != nil {
		return m.TotalPageSize
	}
	return 0
}

type GetPurchaseRequest struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPurchaseRequest) Reset()         { *m = GetPurchaseRequest{} }
func (m *GetPurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*GetPurchaseRequest) ProtoMessage()    {}
func (*GetPurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{11}
}
func (m *GetPurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPurchaseRequest.Unmarshal(m, b)
}
func (m *GetPurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *GetPurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPurchaseRequest.Merge(dst, src)
}
func (m *GetPurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_GetPurchaseRequest.Size(m)
}
func (m *GetPurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPurchaseRequest proto.InternalMessageInfo

func (m *GetPurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type GetPurchaseResponse struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPurchaseResponse) Reset()         { *m = GetPurchaseResponse{} }
func (m *GetPurchaseResponse) String() string { return proto.CompactTextString(m) }
func (*GetPurchaseResponse) ProtoMessage()    {}
func (*GetPurchaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{12}
}
func (m *GetPurchaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPurchaseResponse.Unmarshal(m, b)
}
func (m *GetPurchaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPurchaseResponse.Marshal(b, m, deterministic)
}
func (dst *GetPurchaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPurchaseResponse.Merge(dst, src)
}
func (m *GetPurchaseResponse) XXX_Size() int {
	return xxx_messageInfo_GetPurchaseResponse.Size(m)
}
func (m *GetPurchaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPurchaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPurchaseResponse proto.InternalMessageInfo

func (m *GetPurchaseResponse) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type CreatePurchaseRequest struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePurchaseRequest) Reset()         { *m = CreatePurchaseRequest{} }
func (m *CreatePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePurchaseRequest) ProtoMessage()    {}
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{13}
}
func (m *CreatePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePurchaseRequest.Unmarshal(m, b)
}
func (m *CreatePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePurchaseRequest.Merge(dst, src)
}
func (m *CreatePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePurchaseRequest.Size(m)
}
func (m *CreatePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePurchaseRequest proto.InternalMessageInfo

func (m *CreatePurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type CreatePurchaseResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePurchaseResponse) Reset()         { *m = CreatePurchaseResponse{} }
func (m *CreatePurchaseResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePurchaseResponse) ProtoMessage()    {}
func (*CreatePurchaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{14}
}
func (m *CreatePurchaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePurchaseResponse.Unmarshal(m, b)
}
func (m *CreatePurchaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePurchaseResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePurchaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePurchaseResponse.Merge(dst, src)
}
func (m *CreatePurchaseResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePurchaseResponse.Size(m)
}
func (m *CreatePurchaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePurchaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePurchaseResponse proto.InternalMessageInfo

func (m *CreatePurchaseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdatePurchaseRequest struct {
	Purchase *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	// or here https://github.com/gogo/grpc-example/commit/6c217371b67a89609c632f047477fa5a1123ac93
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdatePurchaseRequest) Reset()         { *m = UpdatePurchaseRequest{} }
func (m *UpdatePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePurchaseRequest) ProtoMessage()    {}
func (*UpdatePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{15}
}
func (m *UpdatePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePurchaseRequest.Unmarshal(m, b)
}
func (m *UpdatePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePurchaseRequest.Merge(dst, src)
}
func (m *UpdatePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePurchaseRequest.Size(m)
}
func (m *UpdatePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePurchaseRequest proto.InternalMessageInfo

func (m *UpdatePurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

func (m *UpdatePurchaseRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeletePurchaseRequest struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeletePurchaseRequest) Reset()         { *m = DeletePurchaseRequest{} }
func (m *DeletePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePurchaseRequest) ProtoMessage()    {}
func (*DeletePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{16}
}
func (m *DeletePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePurchaseRequest.Unmarshal(m, b)
}
func (m *DeletePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePurchaseRequest.Merge(dst, src)
}
func (m *DeletePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePurchaseRequest.Size(m)
}
func (m *DeletePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePurchaseRequest proto.InternalMessageInfo

func (m *DeletePurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type Purchase struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FlatId               string   `protobuf:"bytes,2,opt,name=flat_id,json=flatId,proto3" json:"flat_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BuyerId              string   `protobuf:"bytes,4,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Shop                 string   `protobuf:"bytes,5,opt,name=shop,proto3" json:"shop,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc                 string   `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Purchase) Reset()         { *m = Purchase{} }
func (m *Purchase) String() string { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()    {}
func (*Purchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_7b7dc8b396dc5eae, []int{17}
}
func (m *Purchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Purchase.Unmarshal(m, b)
}
func (m *Purchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Purchase.Marshal(b, m, deterministic)
}
func (dst *Purchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Purchase.Merge(dst, src)
}
func (m *Purchase) XXX_Size() int {
	return xxx_messageInfo_Purchase.Size(m)
}
func (m *Purchase) XXX_DiscardUnknown() {
	xxx_messageInfo_Purchase.DiscardUnknown(m)
}

var xxx_messageInfo_Purchase proto.InternalMessageInfo

func (m *Purchase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Purchase) GetFlatId() string {
	if m != nil {
		return m.FlatId
	}
	return ""
}

func (m *Purchase) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Purchase) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *Purchase) GetShop() string {
	if m != nil {
		return m.Shop
	}
	return ""
}

func (m *Purchase) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Purchase) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Purchase) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*ListFlatsRequest)(nil), "flatsharing.v1.ListFlatsRequest")
	proto.RegisterType((*ListFlatsResponse)(nil), "flatsharing.v1.ListFlatsResponse")
	proto.RegisterType((*GetFlatRequest)(nil), "flatsharing.v1.GetFlatRequest")
	proto.RegisterType((*GetFlatResponse)(nil), "flatsharing.v1.GetFlatResponse")
	proto.RegisterType((*CreateFlatRequest)(nil), "flatsharing.v1.CreateFlatRequest")
	proto.RegisterType((*CreateFlatResponse)(nil), "flatsharing.v1.CreateFlatResponse")
	proto.RegisterType((*UpdateFlatRequest)(nil), "flatsharing.v1.UpdateFlatRequest")
	proto.RegisterType((*DeleteFlatRequest)(nil), "flatsharing.v1.DeleteFlatRequest")
	proto.RegisterType((*Flat)(nil), "flatsharing.v1.Flat")
	proto.RegisterType((*ListPurchasesRequest)(nil), "flatsharing.v1.ListPurchasesRequest")
	proto.RegisterType((*ListPurchasesResponse)(nil), "flatsharing.v1.ListPurchasesResponse")
	proto.RegisterType((*GetPurchaseRequest)(nil), "flatsharing.v1.GetPurchaseRequest")
	proto.RegisterType((*GetPurchaseResponse)(nil), "flatsharing.v1.GetPurchaseResponse")
	proto.RegisterType((*CreatePurchaseRequest)(nil), "flatsharing.v1.CreatePurchaseRequest")
	proto.RegisterType((*CreatePurchaseResponse)(nil), "flatsharing.v1.CreatePurchaseResponse")
	proto.RegisterType((*UpdatePurchaseRequest)(nil), "flatsharing.v1.UpdatePurchaseRequest")
	proto.RegisterType((*DeletePurchaseRequest)(nil), "flatsharing.v1.DeletePurchaseRequest")
	proto.RegisterType((*Purchase)(nil), "flatsharing.v1.Purchase")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlatServicesClient is the client API for FlatServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlatServicesClient interface {
	ListFlats(ctx context.Context, in *ListFlatsRequest, opts ...grpc.CallOption) (*ListFlatsResponse, error)
	GetFlat(ctx context.Context, in *GetFlatRequest, opts ...grpc.CallOption) (*GetFlatResponse, error)
	CreateFlat(ctx context.Context, in *CreateFlatRequest, opts ...grpc.CallOption) (*CreateFlatResponse, error)
	UpdateFlat(ctx context.Context, in *UpdateFlatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteFlat(ctx context.Context, in *DeleteFlatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type flatServicesClient struct {
	cc *grpc.ClientConn
}

func NewFlatServicesClient(cc *grpc.ClientConn) FlatServicesClient {
	return &flatServicesClient{cc}
}

func (c *flatServicesClient) ListFlats(ctx context.Context, in *ListFlatsRequest, opts ...grpc.CallOption) (*ListFlatsResponse, error) {
	out := new(ListFlatsResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.FlatServices/ListFlats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flatServicesClient) GetFlat(ctx context.Context, in *GetFlatRequest, opts ...grpc.CallOption) (*GetFlatResponse, error) {
	out := new(GetFlatResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.FlatServices/GetFlat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flatServicesClient) CreateFlat(ctx context.Context, in *CreateFlatRequest, opts ...grpc.CallOption) (*CreateFlatResponse, error) {
	out := new(CreateFlatResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.FlatServices/CreateFlat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flatServicesClient) UpdateFlat(ctx context.Context, in *UpdateFlatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.FlatServices/UpdateFlat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flatServicesClient) DeleteFlat(ctx context.Context, in *DeleteFlatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.FlatServices/DeleteFlat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlatServicesServer is the server API for FlatServices service.
type FlatServicesServer interface {
	ListFlats(context.Context, *ListFlatsRequest) (*ListFlatsResponse, error)
	GetFlat(context.Context, *GetFlatRequest) (*GetFlatResponse, error)
	CreateFlat(context.Context, *CreateFlatRequest) (*CreateFlatResponse, error)
	UpdateFlat(context.Context, *UpdateFlatRequest) (*empty.Empty, error)
	DeleteFlat(context.Context, *DeleteFlatRequest) (*empty.Empty, error)
}

func RegisterFlatServicesServer(s *grpc.Server, srv FlatServicesServer) {
	s.RegisterService(&_FlatServices_serviceDesc, srv)
}

func _FlatServices_ListFlats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlatServicesServer).ListFlats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.FlatServices/ListFlats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlatServicesServer).ListFlats(ctx, req.(*ListFlatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlatServices_GetFlat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlatServicesServer).GetFlat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.FlatServices/GetFlat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlatServicesServer).GetFlat(ctx, req.(*GetFlatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlatServices_CreateFlat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlatServicesServer).CreateFlat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.FlatServices/CreateFlat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlatServicesServer).CreateFlat(ctx, req.(*CreateFlatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlatServices_UpdateFlat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlatServicesServer).UpdateFlat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.FlatServices/UpdateFlat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlatServicesServer).UpdateFlat(ctx, req.(*UpdateFlatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlatServices_DeleteFlat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlatServicesServer).DeleteFlat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.FlatServices/DeleteFlat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlatServicesServer).DeleteFlat(ctx, req.(*DeleteFlatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlatServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flatsharing.v1.FlatServices",
	HandlerType: (*FlatServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFlats",
			Handler:    _FlatServices_ListFlats_Handler,
		},
		{
			MethodName: "GetFlat",
			Handler:    _FlatServices_GetFlat_Handler,
		},
		{
			MethodName: "CreateFlat",
			Handler:    _FlatServices_CreateFlat_Handler,
		},
		{
			MethodName: "UpdateFlat",
			Handler:    _FlatServices_UpdateFlat_Handler,
		},
		{
			MethodName: "DeleteFlat",
			Handler:    _FlatServices_DeleteFlat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flatsharing.proto",
}

// PurchaseServicesClient is the client API for PurchaseServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PurchaseServicesClient interface {
	ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error)
	GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error)
	CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error)
	UpdatePurchase(ctx context.Context, in *UpdatePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeletePurchase(ctx context.Context, in *DeletePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type purchaseServicesClient struct {
	cc *grpc.ClientConn
}

func NewPurchaseServicesClient(cc *grpc.ClientConn) PurchaseServicesClient {
	return &purchaseServicesClient{cc}
}

func (c *purchaseServicesClient) ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error) {
	out := new(ListPurchasesResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/ListPurchases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error) {
	out := new(GetPurchaseResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/GetPurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error) {
	out := new(CreatePurchaseResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/CreatePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) UpdatePurchase(ctx context.Context, in *UpdatePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/UpdatePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) DeletePurchase(ctx context.Context, in *DeletePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/DeletePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseServicesServer is the server API for PurchaseServices service.
type PurchaseServicesServer interface {
	ListPurchases(context.Context, *ListPurchasesRequest) (*ListPurchasesResponse, error)
	GetPurchase(context.Context, *GetPurchaseRequest) (*GetPurchaseResponse, error)
	CreatePurchase(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error)
	UpdatePurchase(context.Context, *UpdatePurchaseRequest) (*empty.Empty, error)
	DeletePurchase(context.Context, *DeletePurchaseRequest) (*empty.Empty, error)
}

func RegisterPurchaseServicesServer(s *grpc.Server, srv PurchaseServicesServer) {
	s.RegisterService(&_PurchaseServices_serviceDesc, srv)
}

func _PurchaseServices_ListPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPurchasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).ListPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/ListPurchases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).ListPurchases(ctx, req.(*ListPurchasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_GetPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).GetPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/GetPurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).GetPurchase(ctx, req.(*GetPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_CreatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).CreatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/CreatePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).CreatePurchase(ctx, req.(*CreatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_UpdatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).UpdatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/UpdatePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).UpdatePurchase(ctx, req.(*UpdatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_DeletePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).DeletePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/DeletePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).DeletePurchase(ctx, req.(*DeletePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PurchaseServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flatsharing.v1.PurchaseServices",
	HandlerType: (*PurchaseServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPurchases",
			Handler:    _PurchaseServices_ListPurchases_Handler,
		},
		{
			MethodName: "GetPurchase",
			Handler:    _PurchaseServices_GetPurchase_Handler,
		},
		{
			MethodName: "CreatePurchase",
			Handler:    _PurchaseServices_CreatePurchase_Handler,
		},
		{
			MethodName: "UpdatePurchase",
			Handler:    _PurchaseServices_UpdatePurchase_Handler,
		},
		{
			MethodName: "DeletePurchase",
			Handler:    _PurchaseServices_DeletePurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flatsharing.proto",
}

func init() { proto.RegisterFile("flatsharing.proto", fileDescriptor_flatsharing_7b7dc8b396dc5eae) }

var fileDescriptor_flatsharing_7b7dc8b396dc5eae = []byte{
	// 880 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xe2, 0x48,
	0x10, 0x96, 0x09, 0xe1, 0xa7, 0x08, 0x24, 0x74, 0x20, 0x38, 0x4e, 0xb2, 0x61, 0xbd, 0x49, 0x84,
	0x72, 0xc0, 0x0a, 0xbb, 0xa7, 0x44, 0x7b, 0xd8, 0xbf, 0x44, 0xec, 0x6e, 0x56, 0x91, 0xb3, 0x7b,
	0xd9, 0x0b, 0x32, 0xb8, 0x01, 0x2b, 0x60, 0x7b, 0xed, 0x06, 0x25, 0x44, 0x7b, 0x99, 0xe3, 0x48,
	0x73, 0x18, 0xcd, 0x79, 0x5e, 0x67, 0x5e, 0x60, 0x5e, 0x61, 0x2e, 0xf3, 0x16, 0xa3, 0x6e, 0xb7,
	0x01, 0xff, 0x40, 0xa2, 0x0c, 0x17, 0xe4, 0xae, 0xaa, 0xae, 0xef, 0xab, 0xee, 0xaf, 0xaa, 0x81,
	0x62, 0x77, 0xa0, 0x11, 0xb7, 0xaf, 0x39, 0x86, 0xd9, 0xab, 0xdb, 0x8e, 0x45, 0x2c, 0x54, 0x98,
	0x37, 0x8d, 0xcf, 0xa4, 0xbd, 0x9e, 0x65, 0xf5, 0x06, 0x58, 0x61, 0xde, 0xf6, 0xa8, 0xab, 0xe0,
	0xa1, 0x4d, 0x1e, 0xbc, 0x60, 0xa9, 0x1a, 0x76, 0x76, 0x0d, 0x3c, 0xd0, 0x5b, 0x43, 0xcd, 0xbd,
	0xe3, 0x11, 0xfb, 0x3c, 0x42, 0xb3, 0x0d, 0x45, 0x33, 0x4d, 0x8b, 0x68, 0xc4, 0xb0, 0x4c, 0xd7,
	0xf3, 0xca, 0x7f, 0xc1, 0xd6, 0x9f, 0x86, 0x4b, 0x2e, 0x29, 0xa4, 0x8a, 0xff, 0x1b, 0x61, 0x97,
	0xa0, 0x3d, 0xc8, 0xda, 0x5a, 0x0f, 0xb7, 0x5c, 0x63, 0x82, 0x45, 0xa1, 0x2a, 0xd4, 0xd6, 0xd5,
	0x0c, 0x35, 0xdc, 0x1a, 0x13, 0x8c, 0x0e, 0x00, 0x98, 0x93, 0x58, 0x77, 0xd8, 0x14, 0x13, 0x55,
	0xa1, 0x96, 0x55, 0x59, 0xf8, 0xdf, 0xd4, 0x20, 0xbf, 0x11, 0xa0, 0x38, 0x97, 0xd0, 0xb5, 0x2d,
	0xd3, 0xc5, 0xa8, 0x06, 0x49, 0x5a, 0x94, 0x28, 0x54, 0xd7, 0x6a, 0xb9, 0x46, 0xa9, 0x1e, 0xac,
	0xb0, 0x4e, 0x83, 0x55, 0x16, 0x81, 0x4e, 0x60, 0xd3, 0xc4, 0xf7, 0xa4, 0x15, 0xc1, 0xc8, 0x53,
	0xf3, 0x8d, 0x8f, 0x43, 0xe3, 0x88, 0x45, 0xb4, 0x41, 0x6b, 0xc6, 0x74, 0x8d, 0x31, 0xcd, 0x33,
	0xf3, 0x0d, 0xa7, 0x2b, 0x9f, 0x43, 0xe1, 0x0a, 0x33, 0x36, 0x7e, 0x75, 0x33, 0x2e, 0xc2, 0x72,
	0x2e, 0xf2, 0x05, 0x6c, 0x4e, 0xf7, 0x46, 0x0a, 0x79, 0x6a, 0xf3, 0x8f, 0x50, 0xfc, 0xc5, 0xc1,
	0x1a, 0xc1, 0x2f, 0xc3, 0x3e, 0x02, 0x34, 0xbf, 0x9d, 0xc3, 0x17, 0x20, 0x61, 0xe8, 0x6c, 0x77,
	0x56, 0x4d, 0x18, 0xba, 0x3c, 0x81, 0xe2, 0x3f, 0xb6, 0xfe, 0x52, 0x10, 0x74, 0x01, 0xb9, 0x11,
	0xdb, 0xce, 0xf4, 0xc2, 0x0e, 0x3a, 0xd7, 0x90, 0xea, 0x9e, 0x60, 0xea, 0xbe, 0xa4, 0xea, 0x97,
	0x54, 0x52, 0xd7, 0x9a, 0x7b, 0xa7, 0x82, 0x17, 0x4e, 0xbf, 0x69, 0x81, 0xbf, 0xe2, 0x01, 0x7e,
	0x69, 0x81, 0x4d, 0x48, 0xd2, 0x55, 0xb8, 0x24, 0x84, 0x20, 0x69, 0x6a, 0x43, 0xcc, 0x6f, 0x9d,
	0x7d, 0x53, 0xcd, 0x75, 0xd8, 0x61, 0xe8, 0x2d, 0x8d, 0x88, 0x59, 0x4f, 0x73, 0xdc, 0xf2, 0x13,
	0x91, 0x55, 0x28, 0x51, 0xc9, 0xdd, 0x8c, 0x9c, 0x4e, 0x5f, 0x73, 0xf1, 0x4a, 0x74, 0xfc, 0x5e,
	0x80, 0x72, 0x28, 0x29, 0xbf, 0x83, 0x1f, 0x20, 0x63, 0x73, 0x23, 0xd7, 0xb3, 0x18, 0x2e, 0xd3,
	0xdf, 0xa4, 0x4e, 0x23, 0x57, 0xae, 0xeb, 0xdf, 0x01, 0x5d, 0xe1, 0x29, 0x3b, 0xbf, 0xe2, 0x20,
	0x37, 0xe1, 0x79, 0xdc, 0xe4, 0x3f, 0x60, 0x3b, 0x90, 0x2b, 0xb6, 0xd0, 0xe7, 0x26, 0xbb, 0x86,
	0xb2, 0x27, 0xdc, 0xd5, 0x70, 0xab, 0xc1, 0x4e, 0x38, 0xdd, 0x82, 0x5e, 0x78, 0x2d, 0x40, 0xd9,
	0x6b, 0x86, 0x95, 0x20, 0x7f, 0x5d, 0x73, 0x5c, 0x43, 0xd9, 0x6b, 0x8e, 0xd5, 0x9c, 0xc2, 0x07,
	0x01, 0x32, 0xbe, 0x39, 0xd2, 0x31, 0x15, 0x48, 0xd3, 0x0c, 0x2d, 0x43, 0xe7, 0x92, 0x4a, 0xd1,
	0x65, 0x93, 0x39, 0x46, 0x2e, 0x76, 0xa8, 0x63, 0xcd, 0x73, 0xd0, 0x65, 0x53, 0x47, 0xbb, 0x90,
	0x69, 0x8f, 0x1e, 0x3c, 0x4f, 0x92, 0x79, 0xd2, 0x6c, 0xdd, 0x64, 0xed, 0xe7, 0xf6, 0x2d, 0x5b,
	0x5c, 0xf7, 0xda, 0x8f, 0x7e, 0xa3, 0x1d, 0x48, 0x69, 0x43, 0x6b, 0x64, 0x12, 0x31, 0xe5, 0xa5,
	0xf1, 0x56, 0x34, 0x56, 0xc7, 0x6e, 0x47, 0x4c, 0x7b, 0xb1, 0xf4, 0x3b, 0xd4, 0xaa, 0x99, 0x50,
	0xab, 0x36, 0xde, 0x26, 0x61, 0x83, 0xb6, 0xfd, 0x2d, 0x76, 0xc6, 0x46, 0x07, 0xbb, 0xa8, 0x0d,
	0xd9, 0xe9, 0x73, 0x81, 0xaa, 0xe1, 0xa3, 0x08, 0x3f, 0x4d, 0xd2, 0xb7, 0x4b, 0x22, 0x3c, 0x5d,
	0xc8, 0x5b, 0xaf, 0x3e, 0x7e, 0x7a, 0x97, 0x00, 0x94, 0x51, 0xc6, 0x67, 0x0a, 0x1b, 0x73, 0x5d,
	0x48, 0xf3, 0x39, 0x8e, 0xbe, 0x09, 0xef, 0x0f, 0x3e, 0x0e, 0xd2, 0xe1, 0x42, 0x3f, 0xcf, 0x2e,
	0xb1, 0xec, 0x25, 0x84, 0xfc, 0xec, 0xca, 0x23, 0xfd, 0xad, 0x1b, 0xfa, 0xff, 0xa8, 0x0f, 0x30,
	0x9b, 0xd9, 0x28, 0x42, 0x35, 0xf2, 0x1c, 0x48, 0xf2, 0xb2, 0x10, 0x0e, 0xb8, 0xcd, 0x00, 0xf3,
	0xf2, 0xb4, 0x9c, 0x73, 0xe1, 0x14, 0x75, 0x01, 0x66, 0x73, 0x3f, 0x8a, 0x14, 0x79, 0x13, 0xa4,
	0x9d, 0x88, 0x6e, 0x7f, 0xa3, 0x7f, 0x22, 0xe4, 0x03, 0x96, 0xbd, 0x22, 0xc5, 0x94, 0x43, 0x71,
	0x3a, 0x00, 0xb3, 0x19, 0x1f, 0xc5, 0x89, 0xcc, 0xff, 0x85, 0x38, 0xfc, 0xd8, 0x4e, 0x63, 0x70,
	0x1a, 0x9f, 0x93, 0xb0, 0xe5, 0x8b, 0x7b, 0xaa, 0x0b, 0x07, 0xf2, 0x81, 0xf1, 0x8b, 0x8e, 0xe2,
	0x6e, 0x3e, 0x3c, 0xf2, 0xa5, 0xe3, 0x27, 0xa2, 0xf8, 0xa1, 0x96, 0x18, 0x9d, 0x02, 0xda, 0xa0,
	0x74, 0xa6, 0x1d, 0x3f, 0x81, 0xdc, 0xdc, 0x1c, 0x44, 0x72, 0x8c, 0x16, 0x42, 0xed, 0x2c, 0x7d,
	0xb7, 0x34, 0x86, 0xa3, 0xc9, 0x0c, 0x6d, 0x1f, 0x49, 0xf3, 0x68, 0xca, 0xa3, 0xff, 0xc5, 0xb4,
	0x73, 0x0f, 0x85, 0xe0, 0x9c, 0x43, 0xc7, 0xf1, 0xe2, 0x08, 0x33, 0x38, 0x79, 0x2a, 0x8c, 0x93,
	0xa8, 0x30, 0x12, 0x45, 0x39, 0x50, 0x32, 0xbd, 0xe3, 0x31, 0x14, 0x82, 0x63, 0x33, 0x8a, 0x1c,
	0x3b, 0x56, 0x17, 0xde, 0xf5, 0x31, 0x43, 0x3a, 0x94, 0x96, 0x94, 0x4b, 0x71, 0x5d, 0x28, 0x04,
	0x47, 0x64, 0x14, 0x37, 0x76, 0x84, 0x2e, 0xc4, 0xe5, 0xc7, 0x7c, 0xba, 0x04, 0xf7, 0xe7, 0xdd,
	0x7f, 0x2b, 0x86, 0x49, 0xb0, 0x63, 0x6a, 0x03, 0x65, 0x0e, 0x4c, 0x19, 0x9f, 0xb5, 0x53, 0x2c,
	0xdd, 0xf7, 0x5f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x77, 0x9b, 0xb5, 0xbd, 0x92, 0x0b, 0x00, 0x00,
}
