// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flatsharing.proto

package v1 // import "internal/flatsharing/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListHomesRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHomesRequest) Reset()         { *m = ListHomesRequest{} }
func (m *ListHomesRequest) String() string { return proto.CompactTextString(m) }
func (*ListHomesRequest) ProtoMessage()    {}
func (*ListHomesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{0}
}
func (m *ListHomesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHomesRequest.Unmarshal(m, b)
}
func (m *ListHomesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHomesRequest.Marshal(b, m, deterministic)
}
func (dst *ListHomesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHomesRequest.Merge(dst, src)
}
func (m *ListHomesRequest) XXX_Size() int {
	return xxx_messageInfo_ListHomesRequest.Size(m)
}
func (m *ListHomesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHomesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHomesRequest proto.InternalMessageInfo

func (m *ListHomesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListHomesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListHomesResponse struct {
	// See https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/monitoring/apiv3/metric_client.go#L137
	Home                 []*Home  `protobuf:"bytes,1,rep,name=home,proto3" json:"home,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalPageSize        int32    `protobuf:"varint,3,opt,name=total_page_size,json=totalPageSize,proto3" json:"total_page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHomesResponse) Reset()         { *m = ListHomesResponse{} }
func (m *ListHomesResponse) String() string { return proto.CompactTextString(m) }
func (*ListHomesResponse) ProtoMessage()    {}
func (*ListHomesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{1}
}
func (m *ListHomesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHomesResponse.Unmarshal(m, b)
}
func (m *ListHomesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHomesResponse.Marshal(b, m, deterministic)
}
func (dst *ListHomesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHomesResponse.Merge(dst, src)
}
func (m *ListHomesResponse) XXX_Size() int {
	return xxx_messageInfo_ListHomesResponse.Size(m)
}
func (m *ListHomesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHomesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHomesResponse proto.InternalMessageInfo

func (m *ListHomesResponse) GetHome() []*Home {
	if m != nil {
		return m.Home
	}
	return nil
}

func (m *ListHomesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListHomesResponse) GetTotalPageSize() int32 {
	if m != nil {
		return m.TotalPageSize
	}
	return 0
}

type GetHomeRequest struct {
	Home                 *Home    `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHomeRequest) Reset()         { *m = GetHomeRequest{} }
func (m *GetHomeRequest) String() string { return proto.CompactTextString(m) }
func (*GetHomeRequest) ProtoMessage()    {}
func (*GetHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{2}
}
func (m *GetHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeRequest.Unmarshal(m, b)
}
func (m *GetHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeRequest.Marshal(b, m, deterministic)
}
func (dst *GetHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeRequest.Merge(dst, src)
}
func (m *GetHomeRequest) XXX_Size() int {
	return xxx_messageInfo_GetHomeRequest.Size(m)
}
func (m *GetHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeRequest proto.InternalMessageInfo

func (m *GetHomeRequest) GetHome() *Home {
	if m != nil {
		return m.Home
	}
	return nil
}

type GetHomeResponse struct {
	Home                 *Home    `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHomeResponse) Reset()         { *m = GetHomeResponse{} }
func (m *GetHomeResponse) String() string { return proto.CompactTextString(m) }
func (*GetHomeResponse) ProtoMessage()    {}
func (*GetHomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{3}
}
func (m *GetHomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeResponse.Unmarshal(m, b)
}
func (m *GetHomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeResponse.Marshal(b, m, deterministic)
}
func (dst *GetHomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeResponse.Merge(dst, src)
}
func (m *GetHomeResponse) XXX_Size() int {
	return xxx_messageInfo_GetHomeResponse.Size(m)
}
func (m *GetHomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeResponse proto.InternalMessageInfo

func (m *GetHomeResponse) GetHome() *Home {
	if m != nil {
		return m.Home
	}
	return nil
}

type CreateHomeRequest struct {
	Home                 *Home    `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHomeRequest) Reset()         { *m = CreateHomeRequest{} }
func (m *CreateHomeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHomeRequest) ProtoMessage()    {}
func (*CreateHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{4}
}
func (m *CreateHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHomeRequest.Unmarshal(m, b)
}
func (m *CreateHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHomeRequest.Marshal(b, m, deterministic)
}
func (dst *CreateHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHomeRequest.Merge(dst, src)
}
func (m *CreateHomeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHomeRequest.Size(m)
}
func (m *CreateHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHomeRequest proto.InternalMessageInfo

func (m *CreateHomeRequest) GetHome() *Home {
	if m != nil {
		return m.Home
	}
	return nil
}

type CreateHomeResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHomeResponse) Reset()         { *m = CreateHomeResponse{} }
func (m *CreateHomeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateHomeResponse) ProtoMessage()    {}
func (*CreateHomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{5}
}
func (m *CreateHomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHomeResponse.Unmarshal(m, b)
}
func (m *CreateHomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHomeResponse.Marshal(b, m, deterministic)
}
func (dst *CreateHomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHomeResponse.Merge(dst, src)
}
func (m *CreateHomeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHomeResponse.Size(m)
}
func (m *CreateHomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHomeResponse proto.InternalMessageInfo

func (m *CreateHomeResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateHomeRequest struct {
	Home *Home `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	// or here https://github.com/gogo/grpc-example/commit/6c217371b67a89609c632f047477fa5a1123ac93
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateHomeRequest) Reset()         { *m = UpdateHomeRequest{} }
func (m *UpdateHomeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHomeRequest) ProtoMessage()    {}
func (*UpdateHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{6}
}
func (m *UpdateHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHomeRequest.Unmarshal(m, b)
}
func (m *UpdateHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHomeRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHomeRequest.Merge(dst, src)
}
func (m *UpdateHomeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHomeRequest.Size(m)
}
func (m *UpdateHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHomeRequest proto.InternalMessageInfo

func (m *UpdateHomeRequest) GetHome() *Home {
	if m != nil {
		return m.Home
	}
	return nil
}

func (m *UpdateHomeRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteHomeRequest struct {
	Home                 *Home    `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHomeRequest) Reset()         { *m = DeleteHomeRequest{} }
func (m *DeleteHomeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHomeRequest) ProtoMessage()    {}
func (*DeleteHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{7}
}
func (m *DeleteHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHomeRequest.Unmarshal(m, b)
}
func (m *DeleteHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHomeRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHomeRequest.Merge(dst, src)
}
func (m *DeleteHomeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHomeRequest.Size(m)
}
func (m *DeleteHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHomeRequest proto.InternalMessageInfo

func (m *DeleteHomeRequest) GetHome() *Home {
	if m != nil {
		return m.Home
	}
	return nil
}

type Home struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Home) Reset()         { *m = Home{} }
func (m *Home) String() string { return proto.CompactTextString(m) }
func (*Home) ProtoMessage()    {}
func (*Home) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{8}
}
func (m *Home) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Home.Unmarshal(m, b)
}
func (m *Home) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Home.Marshal(b, m, deterministic)
}
func (dst *Home) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Home.Merge(dst, src)
}
func (m *Home) XXX_Size() int {
	return xxx_messageInfo_Home.Size(m)
}
func (m *Home) XXX_DiscardUnknown() {
	xxx_messageInfo_Home.DiscardUnknown(m)
}

var xxx_messageInfo_Home proto.InternalMessageInfo

func (m *Home) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Home) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Home) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type ListPurchasesRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPurchasesRequest) Reset()         { *m = ListPurchasesRequest{} }
func (m *ListPurchasesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesRequest) ProtoMessage()    {}
func (*ListPurchasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{9}
}
func (m *ListPurchasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesRequest.Unmarshal(m, b)
}
func (m *ListPurchasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesRequest.Marshal(b, m, deterministic)
}
func (dst *ListPurchasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesRequest.Merge(dst, src)
}
func (m *ListPurchasesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesRequest.Size(m)
}
func (m *ListPurchasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesRequest proto.InternalMessageInfo

func (m *ListPurchasesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPurchasesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListPurchasesResponse struct {
	// See https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/monitoring/apiv3/metric_client.go#L137
	Purchase             []*Purchase `protobuf:"bytes,1,rep,name=purchase,proto3" json:"purchase,omitempty"`
	NextPageToken        string      `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalPageSize        int32       `protobuf:"varint,3,opt,name=total_page_size,json=totalPageSize,proto3" json:"total_page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPurchasesResponse) Reset()         { *m = ListPurchasesResponse{} }
func (m *ListPurchasesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesResponse) ProtoMessage()    {}
func (*ListPurchasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{10}
}
func (m *ListPurchasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesResponse.Unmarshal(m, b)
}
func (m *ListPurchasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesResponse.Marshal(b, m, deterministic)
}
func (dst *ListPurchasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesResponse.Merge(dst, src)
}
func (m *ListPurchasesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesResponse.Size(m)
}
func (m *ListPurchasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesResponse proto.InternalMessageInfo

func (m *ListPurchasesResponse) GetPurchase() []*Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

func (m *ListPurchasesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListPurchasesResponse) GetTotalPageSize() int32 {
	if m != nil {
		return m.TotalPageSize
	}
	return 0
}

type GetPurchaseRequest struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPurchaseRequest) Reset()         { *m = GetPurchaseRequest{} }
func (m *GetPurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*GetPurchaseRequest) ProtoMessage()    {}
func (*GetPurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{11}
}
func (m *GetPurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPurchaseRequest.Unmarshal(m, b)
}
func (m *GetPurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *GetPurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPurchaseRequest.Merge(dst, src)
}
func (m *GetPurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_GetPurchaseRequest.Size(m)
}
func (m *GetPurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPurchaseRequest proto.InternalMessageInfo

func (m *GetPurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type GetPurchaseResponse struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPurchaseResponse) Reset()         { *m = GetPurchaseResponse{} }
func (m *GetPurchaseResponse) String() string { return proto.CompactTextString(m) }
func (*GetPurchaseResponse) ProtoMessage()    {}
func (*GetPurchaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{12}
}
func (m *GetPurchaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPurchaseResponse.Unmarshal(m, b)
}
func (m *GetPurchaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPurchaseResponse.Marshal(b, m, deterministic)
}
func (dst *GetPurchaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPurchaseResponse.Merge(dst, src)
}
func (m *GetPurchaseResponse) XXX_Size() int {
	return xxx_messageInfo_GetPurchaseResponse.Size(m)
}
func (m *GetPurchaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPurchaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPurchaseResponse proto.InternalMessageInfo

func (m *GetPurchaseResponse) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type CreatePurchaseRequest struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePurchaseRequest) Reset()         { *m = CreatePurchaseRequest{} }
func (m *CreatePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePurchaseRequest) ProtoMessage()    {}
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{13}
}
func (m *CreatePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePurchaseRequest.Unmarshal(m, b)
}
func (m *CreatePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePurchaseRequest.Merge(dst, src)
}
func (m *CreatePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePurchaseRequest.Size(m)
}
func (m *CreatePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePurchaseRequest proto.InternalMessageInfo

func (m *CreatePurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type CreatePurchaseResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePurchaseResponse) Reset()         { *m = CreatePurchaseResponse{} }
func (m *CreatePurchaseResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePurchaseResponse) ProtoMessage()    {}
func (*CreatePurchaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{14}
}
func (m *CreatePurchaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePurchaseResponse.Unmarshal(m, b)
}
func (m *CreatePurchaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePurchaseResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePurchaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePurchaseResponse.Merge(dst, src)
}
func (m *CreatePurchaseResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePurchaseResponse.Size(m)
}
func (m *CreatePurchaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePurchaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePurchaseResponse proto.InternalMessageInfo

func (m *CreatePurchaseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdatePurchaseRequest struct {
	Purchase *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	// or here https://github.com/gogo/grpc-example/commit/6c217371b67a89609c632f047477fa5a1123ac93
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdatePurchaseRequest) Reset()         { *m = UpdatePurchaseRequest{} }
func (m *UpdatePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePurchaseRequest) ProtoMessage()    {}
func (*UpdatePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{15}
}
func (m *UpdatePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePurchaseRequest.Unmarshal(m, b)
}
func (m *UpdatePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePurchaseRequest.Merge(dst, src)
}
func (m *UpdatePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePurchaseRequest.Size(m)
}
func (m *UpdatePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePurchaseRequest proto.InternalMessageInfo

func (m *UpdatePurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

func (m *UpdatePurchaseRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeletePurchaseRequest struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeletePurchaseRequest) Reset()         { *m = DeletePurchaseRequest{} }
func (m *DeletePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePurchaseRequest) ProtoMessage()    {}
func (*DeletePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{16}
}
func (m *DeletePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePurchaseRequest.Unmarshal(m, b)
}
func (m *DeletePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePurchaseRequest.Merge(dst, src)
}
func (m *DeletePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePurchaseRequest.Size(m)
}
func (m *DeletePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePurchaseRequest proto.InternalMessageInfo

func (m *DeletePurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type Purchase struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeId               string   `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BuyerId              string   `protobuf:"bytes,4,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Shop                 string   `protobuf:"bytes,5,opt,name=shop,proto3" json:"shop,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc                 string   `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Purchase) Reset()         { *m = Purchase{} }
func (m *Purchase) String() string { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()    {}
func (*Purchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_3989ef66a4568edd, []int{17}
}
func (m *Purchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Purchase.Unmarshal(m, b)
}
func (m *Purchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Purchase.Marshal(b, m, deterministic)
}
func (dst *Purchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Purchase.Merge(dst, src)
}
func (m *Purchase) XXX_Size() int {
	return xxx_messageInfo_Purchase.Size(m)
}
func (m *Purchase) XXX_DiscardUnknown() {
	xxx_messageInfo_Purchase.DiscardUnknown(m)
}

var xxx_messageInfo_Purchase proto.InternalMessageInfo

func (m *Purchase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Purchase) GetHomeId() string {
	if m != nil {
		return m.HomeId
	}
	return ""
}

func (m *Purchase) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Purchase) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *Purchase) GetShop() string {
	if m != nil {
		return m.Shop
	}
	return ""
}

func (m *Purchase) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Purchase) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Purchase) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*ListHomesRequest)(nil), "flatsharing.v1.ListHomesRequest")
	proto.RegisterType((*ListHomesResponse)(nil), "flatsharing.v1.ListHomesResponse")
	proto.RegisterType((*GetHomeRequest)(nil), "flatsharing.v1.GetHomeRequest")
	proto.RegisterType((*GetHomeResponse)(nil), "flatsharing.v1.GetHomeResponse")
	proto.RegisterType((*CreateHomeRequest)(nil), "flatsharing.v1.CreateHomeRequest")
	proto.RegisterType((*CreateHomeResponse)(nil), "flatsharing.v1.CreateHomeResponse")
	proto.RegisterType((*UpdateHomeRequest)(nil), "flatsharing.v1.UpdateHomeRequest")
	proto.RegisterType((*DeleteHomeRequest)(nil), "flatsharing.v1.DeleteHomeRequest")
	proto.RegisterType((*Home)(nil), "flatsharing.v1.Home")
	proto.RegisterType((*ListPurchasesRequest)(nil), "flatsharing.v1.ListPurchasesRequest")
	proto.RegisterType((*ListPurchasesResponse)(nil), "flatsharing.v1.ListPurchasesResponse")
	proto.RegisterType((*GetPurchaseRequest)(nil), "flatsharing.v1.GetPurchaseRequest")
	proto.RegisterType((*GetPurchaseResponse)(nil), "flatsharing.v1.GetPurchaseResponse")
	proto.RegisterType((*CreatePurchaseRequest)(nil), "flatsharing.v1.CreatePurchaseRequest")
	proto.RegisterType((*CreatePurchaseResponse)(nil), "flatsharing.v1.CreatePurchaseResponse")
	proto.RegisterType((*UpdatePurchaseRequest)(nil), "flatsharing.v1.UpdatePurchaseRequest")
	proto.RegisterType((*DeletePurchaseRequest)(nil), "flatsharing.v1.DeletePurchaseRequest")
	proto.RegisterType((*Purchase)(nil), "flatsharing.v1.Purchase")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HomeServicesClient is the client API for HomeServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HomeServicesClient interface {
	ListHomes(ctx context.Context, in *ListHomesRequest, opts ...grpc.CallOption) (*ListHomesResponse, error)
	GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*GetHomeResponse, error)
	CreateHome(ctx context.Context, in *CreateHomeRequest, opts ...grpc.CallOption) (*CreateHomeResponse, error)
	UpdateHome(ctx context.Context, in *UpdateHomeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteHome(ctx context.Context, in *DeleteHomeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type homeServicesClient struct {
	cc *grpc.ClientConn
}

func NewHomeServicesClient(cc *grpc.ClientConn) HomeServicesClient {
	return &homeServicesClient{cc}
}

func (c *homeServicesClient) ListHomes(ctx context.Context, in *ListHomesRequest, opts ...grpc.CallOption) (*ListHomesResponse, error) {
	out := new(ListHomesResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.HomeServices/ListHomes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServicesClient) GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*GetHomeResponse, error) {
	out := new(GetHomeResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.HomeServices/GetHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServicesClient) CreateHome(ctx context.Context, in *CreateHomeRequest, opts ...grpc.CallOption) (*CreateHomeResponse, error) {
	out := new(CreateHomeResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.HomeServices/CreateHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServicesClient) UpdateHome(ctx context.Context, in *UpdateHomeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.HomeServices/UpdateHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServicesClient) DeleteHome(ctx context.Context, in *DeleteHomeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.HomeServices/DeleteHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeServicesServer is the server API for HomeServices service.
type HomeServicesServer interface {
	ListHomes(context.Context, *ListHomesRequest) (*ListHomesResponse, error)
	GetHome(context.Context, *GetHomeRequest) (*GetHomeResponse, error)
	CreateHome(context.Context, *CreateHomeRequest) (*CreateHomeResponse, error)
	UpdateHome(context.Context, *UpdateHomeRequest) (*empty.Empty, error)
	DeleteHome(context.Context, *DeleteHomeRequest) (*empty.Empty, error)
}

func RegisterHomeServicesServer(s *grpc.Server, srv HomeServicesServer) {
	s.RegisterService(&_HomeServices_serviceDesc, srv)
}

func _HomeServices_ListHomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServicesServer).ListHomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.HomeServices/ListHomes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServicesServer).ListHomes(ctx, req.(*ListHomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeServices_GetHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServicesServer).GetHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.HomeServices/GetHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServicesServer).GetHome(ctx, req.(*GetHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeServices_CreateHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServicesServer).CreateHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.HomeServices/CreateHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServicesServer).CreateHome(ctx, req.(*CreateHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeServices_UpdateHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServicesServer).UpdateHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.HomeServices/UpdateHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServicesServer).UpdateHome(ctx, req.(*UpdateHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeServices_DeleteHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServicesServer).DeleteHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.HomeServices/DeleteHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServicesServer).DeleteHome(ctx, req.(*DeleteHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HomeServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flatsharing.v1.HomeServices",
	HandlerType: (*HomeServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHomes",
			Handler:    _HomeServices_ListHomes_Handler,
		},
		{
			MethodName: "GetHome",
			Handler:    _HomeServices_GetHome_Handler,
		},
		{
			MethodName: "CreateHome",
			Handler:    _HomeServices_CreateHome_Handler,
		},
		{
			MethodName: "UpdateHome",
			Handler:    _HomeServices_UpdateHome_Handler,
		},
		{
			MethodName: "DeleteHome",
			Handler:    _HomeServices_DeleteHome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flatsharing.proto",
}

// PurchaseServicesClient is the client API for PurchaseServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PurchaseServicesClient interface {
	ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error)
	GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error)
	CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error)
	UpdatePurchase(ctx context.Context, in *UpdatePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeletePurchase(ctx context.Context, in *DeletePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type purchaseServicesClient struct {
	cc *grpc.ClientConn
}

func NewPurchaseServicesClient(cc *grpc.ClientConn) PurchaseServicesClient {
	return &purchaseServicesClient{cc}
}

func (c *purchaseServicesClient) ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error) {
	out := new(ListPurchasesResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/ListPurchases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error) {
	out := new(GetPurchaseResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/GetPurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error) {
	out := new(CreatePurchaseResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/CreatePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) UpdatePurchase(ctx context.Context, in *UpdatePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/UpdatePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServicesClient) DeletePurchase(ctx context.Context, in *DeletePurchaseRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/DeletePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseServicesServer is the server API for PurchaseServices service.
type PurchaseServicesServer interface {
	ListPurchases(context.Context, *ListPurchasesRequest) (*ListPurchasesResponse, error)
	GetPurchase(context.Context, *GetPurchaseRequest) (*GetPurchaseResponse, error)
	CreatePurchase(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error)
	UpdatePurchase(context.Context, *UpdatePurchaseRequest) (*empty.Empty, error)
	DeletePurchase(context.Context, *DeletePurchaseRequest) (*empty.Empty, error)
}

func RegisterPurchaseServicesServer(s *grpc.Server, srv PurchaseServicesServer) {
	s.RegisterService(&_PurchaseServices_serviceDesc, srv)
}

func _PurchaseServices_ListPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPurchasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).ListPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/ListPurchases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).ListPurchases(ctx, req.(*ListPurchasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_GetPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).GetPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/GetPurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).GetPurchase(ctx, req.(*GetPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_CreatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).CreatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/CreatePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).CreatePurchase(ctx, req.(*CreatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_UpdatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).UpdatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/UpdatePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).UpdatePurchase(ctx, req.(*UpdatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseServices_DeletePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).DeletePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/DeletePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).DeletePurchase(ctx, req.(*DeletePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PurchaseServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flatsharing.v1.PurchaseServices",
	HandlerType: (*PurchaseServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPurchases",
			Handler:    _PurchaseServices_ListPurchases_Handler,
		},
		{
			MethodName: "GetPurchase",
			Handler:    _PurchaseServices_GetPurchase_Handler,
		},
		{
			MethodName: "CreatePurchase",
			Handler:    _PurchaseServices_CreatePurchase_Handler,
		},
		{
			MethodName: "UpdatePurchase",
			Handler:    _PurchaseServices_UpdatePurchase_Handler,
		},
		{
			MethodName: "DeletePurchase",
			Handler:    _PurchaseServices_DeletePurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flatsharing.proto",
}

func init() { proto.RegisterFile("flatsharing.proto", fileDescriptor_flatsharing_3989ef66a4568edd) }

var fileDescriptor_flatsharing_3989ef66a4568edd = []byte{
	// 880 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xea, 0x46,
	0x14, 0x96, 0x09, 0xe1, 0xe7, 0x10, 0x48, 0x98, 0x40, 0x20, 0x4e, 0xd2, 0x50, 0x37, 0x89, 0x50,
	0x16, 0x58, 0xa1, 0x5d, 0x25, 0xea, 0xa2, 0xbf, 0x29, 0x6d, 0x53, 0x45, 0x4e, 0xbb, 0xe9, 0x06,
	0x19, 0x3c, 0x80, 0x15, 0xb0, 0x5d, 0xcf, 0x80, 0x12, 0xa2, 0x6e, 0xba, 0xac, 0xd4, 0x45, 0xd5,
	0x75, 0x5f, 0xe7, 0xbe, 0xc0, 0x7d, 0x85, 0xbb, 0xb9, 0x6f, 0x71, 0x35, 0xe3, 0x31, 0xe0, 0x1f,
	0x48, 0x94, 0xcb, 0x06, 0x79, 0xce, 0x39, 0x73, 0xbe, 0xef, 0xcc, 0x7c, 0xe7, 0x0c, 0x50, 0xec,
	0x0d, 0x75, 0x4a, 0x06, 0xba, 0x6b, 0x5a, 0xfd, 0x86, 0xe3, 0xda, 0xd4, 0x46, 0x85, 0x45, 0xd3,
	0xe4, 0x42, 0x3e, 0xe8, 0xdb, 0x76, 0x7f, 0x88, 0x55, 0xee, 0xed, 0x8c, 0x7b, 0x2a, 0x1e, 0x39,
	0xf4, 0xd1, 0x0b, 0x96, 0x6b, 0x61, 0x67, 0xcf, 0xc4, 0x43, 0xa3, 0x3d, 0xd2, 0xc9, 0xbd, 0x88,
	0x38, 0x14, 0x11, 0xba, 0x63, 0xaa, 0xba, 0x65, 0xd9, 0x54, 0xa7, 0xa6, 0x6d, 0x11, 0xcf, 0xab,
	0xfc, 0x02, 0x3b, 0x3f, 0x9b, 0x84, 0xfe, 0x60, 0x8f, 0x30, 0xd1, 0xf0, 0x1f, 0x63, 0x4c, 0x28,
	0x3a, 0x80, 0xac, 0xa3, 0xf7, 0x71, 0x9b, 0x98, 0x53, 0x5c, 0x95, 0x6a, 0x52, 0x7d, 0x53, 0xcb,
	0x30, 0xc3, 0x9d, 0x39, 0xc5, 0xe8, 0x08, 0x80, 0x3b, 0xa9, 0x7d, 0x8f, 0xad, 0x6a, 0xa2, 0x26,
	0xd5, 0xb3, 0x1a, 0x0f, 0xff, 0x95, 0x19, 0x94, 0x7f, 0x24, 0x28, 0x2e, 0x24, 0x24, 0x8e, 0x6d,
	0x11, 0x8c, 0xea, 0x90, 0x1c, 0xd8, 0x23, 0x96, 0x6c, 0xa3, 0x9e, 0x6b, 0x96, 0x1a, 0xc1, 0x0a,
	0x1b, 0x2c, 0x58, 0xe3, 0x11, 0xe8, 0x0c, 0xb6, 0x2d, 0xfc, 0x40, 0xdb, 0x11, 0x8c, 0x3c, 0x33,
	0xdf, 0xfa, 0x38, 0x2c, 0x8e, 0xda, 0x54, 0x1f, 0xb6, 0xe7, 0x4c, 0x37, 0x38, 0xd3, 0x3c, 0x37,
	0xdf, 0x0a, 0xba, 0xca, 0x25, 0x14, 0xae, 0x31, 0x67, 0xe3, 0x57, 0x37, 0xe7, 0x22, 0xad, 0xe6,
	0xa2, 0x5c, 0xc1, 0xf6, 0x6c, 0x6f, 0xa4, 0x90, 0xe7, 0x36, 0x7f, 0x09, 0xc5, 0x6f, 0x5c, 0xac,
	0x53, 0xfc, 0x3a, 0xec, 0x13, 0x40, 0x8b, 0xdb, 0x05, 0x7c, 0x01, 0x12, 0xa6, 0xc1, 0x77, 0x67,
	0xb5, 0x84, 0x69, 0x28, 0x53, 0x28, 0xfe, 0xe6, 0x18, 0xaf, 0x05, 0x41, 0x57, 0x90, 0x1b, 0xf3,
	0xed, 0x5c, 0x2f, 0xfc, 0xa0, 0x73, 0x4d, 0xb9, 0xe1, 0x09, 0xa6, 0xe1, 0x4b, 0xaa, 0xf1, 0x3d,
	0x93, 0xd4, 0x8d, 0x4e, 0xee, 0x35, 0xf0, 0xc2, 0xd9, 0x37, 0x2b, 0xf0, 0x5b, 0x3c, 0xc4, 0xaf,
	0x2d, 0xb0, 0x05, 0x49, 0xb6, 0x0a, 0x97, 0x84, 0x10, 0x24, 0x2d, 0x7d, 0x84, 0xc5, 0xad, 0xf3,
	0x6f, 0xa6, 0xb9, 0x2e, 0x3f, 0x0c, 0xa3, 0xad, 0xd3, 0x6a, 0xd6, 0xd3, 0x9c, 0xb0, 0x7c, 0x45,
	0x15, 0x0d, 0x4a, 0x4c, 0x72, 0xb7, 0x63, 0xb7, 0x3b, 0xd0, 0xc9, 0x7a, 0x74, 0xfc, 0xbf, 0x04,
	0xe5, 0x50, 0x52, 0x71, 0x07, 0x5f, 0x40, 0xc6, 0x11, 0x46, 0xa1, 0xe7, 0x6a, 0xb8, 0x4c, 0x7f,
	0x93, 0x36, 0x8b, 0x5c, 0xbb, 0xae, 0x7f, 0x04, 0x74, 0x8d, 0x67, 0xec, 0xfc, 0x8a, 0x83, 0xdc,
	0xa4, 0x97, 0x71, 0x53, 0x7e, 0x82, 0xdd, 0x40, 0xae, 0xd8, 0x42, 0x5f, 0x9a, 0xec, 0x06, 0xca,
	0x9e, 0x70, 0xd7, 0xc3, 0xad, 0x0e, 0x7b, 0xe1, 0x74, 0x4b, 0x7a, 0xe1, 0x6f, 0x09, 0xca, 0x5e,
	0x33, 0xac, 0x05, 0xf9, 0xe3, 0x9a, 0xe3, 0x06, 0xca, 0x5e, 0x73, 0xac, 0xe7, 0x14, 0xde, 0x48,
	0x90, 0xf1, 0xcd, 0x91, 0x8e, 0xa9, 0x40, 0x9a, 0x75, 0x54, 0xdb, 0x34, 0x84, 0xa4, 0x52, 0x6c,
	0xd9, 0xe2, 0x8e, 0x31, 0xc1, 0x2e, 0x73, 0x6c, 0x78, 0x0e, 0xb6, 0x6c, 0x19, 0x68, 0x1f, 0x32,
	0x9d, 0xf1, 0xa3, 0xe7, 0x49, 0x72, 0x4f, 0x9a, 0xaf, 0x5b, 0xbc, 0xfd, 0xc8, 0xc0, 0x76, 0xaa,
	0x9b, 0x5e, 0xfb, 0xb1, 0x6f, 0xb4, 0x07, 0x29, 0x7d, 0x64, 0x8f, 0x2d, 0x5a, 0x4d, 0x79, 0x69,
	0xbc, 0x15, 0x8b, 0x35, 0x30, 0xe9, 0x56, 0xd3, 0x5e, 0x2c, 0xfb, 0x0e, 0xb5, 0x6a, 0x26, 0xd4,
	0xaa, 0xcd, 0x7f, 0x93, 0xb0, 0xc5, 0xda, 0xfe, 0x0e, 0xbb, 0x13, 0xb3, 0x8b, 0x09, 0xea, 0x40,
	0x76, 0xf6, 0x5c, 0xa0, 0x5a, 0xf8, 0x28, 0xc2, 0x4f, 0x93, 0xfc, 0xe9, 0x8a, 0x08, 0x4f, 0x17,
	0xca, 0xce, 0x5f, 0x6f, 0xdf, 0xfd, 0x97, 0x00, 0x94, 0x51, 0x27, 0x17, 0x2a, 0x1f, 0x73, 0x3d,
	0x48, 0x8b, 0x39, 0x8e, 0x3e, 0x09, 0xef, 0x0f, 0x3e, 0x0e, 0xf2, 0xf1, 0x52, 0xbf, 0xc8, 0x2e,
	0xf3, 0xec, 0x25, 0x84, 0xfc, 0xec, 0xea, 0x13, 0xfb, 0x6d, 0x98, 0xc6, 0x9f, 0x68, 0x00, 0x30,
	0x9f, 0xd9, 0x28, 0x42, 0x35, 0xf2, 0x1c, 0xc8, 0xca, 0xaa, 0x10, 0x01, 0xb8, 0xcb, 0x01, 0xf3,
	0xca, 0xac, 0x9c, 0x4b, 0xe9, 0x1c, 0xf5, 0x00, 0xe6, 0x73, 0x3f, 0x8a, 0x14, 0x79, 0x13, 0xe4,
	0xbd, 0x88, 0x6e, 0xbf, 0x63, 0x7f, 0x22, 0x94, 0x23, 0x9e, 0xbd, 0x22, 0xc7, 0x94, 0xc3, 0x70,
	0xba, 0x00, 0xf3, 0x19, 0x1f, 0xc5, 0x89, 0xcc, 0xff, 0xa5, 0x38, 0xe2, 0xd8, 0xce, 0x63, 0x70,
	0x9a, 0xef, 0x93, 0xb0, 0xe3, 0x8b, 0x7b, 0xa6, 0x0b, 0x17, 0xf2, 0x81, 0xf1, 0x8b, 0x4e, 0xe2,
	0x6e, 0x3e, 0x3c, 0xf2, 0xe5, 0xd3, 0x67, 0xa2, 0xc4, 0xa1, 0x96, 0x38, 0x9d, 0x02, 0xda, 0x62,
	0x74, 0x66, 0x1d, 0x3f, 0x85, 0xdc, 0xc2, 0x1c, 0x44, 0x4a, 0x8c, 0x16, 0x42, 0xed, 0x2c, 0x7f,
	0xb6, 0x32, 0x46, 0xa0, 0x29, 0x1c, 0xed, 0x10, 0xc9, 0x8b, 0x68, 0xea, 0x93, 0xff, 0xc5, 0xb5,
	0xf3, 0x00, 0x85, 0xe0, 0x9c, 0x43, 0xa7, 0xf1, 0xe2, 0x08, 0x33, 0x38, 0x7b, 0x2e, 0x4c, 0x90,
	0xa8, 0x70, 0x12, 0x45, 0x25, 0x50, 0x32, 0xbb, 0xe3, 0x09, 0x14, 0x82, 0x63, 0x33, 0x8a, 0x1c,
	0x3b, 0x56, 0x97, 0xde, 0xf5, 0x29, 0x47, 0x3a, 0x96, 0x57, 0x94, 0xcb, 0x70, 0x09, 0x14, 0x82,
	0x23, 0x32, 0x8a, 0x1b, 0x3b, 0x42, 0x97, 0xe2, 0x8a, 0x63, 0x3e, 0x5f, 0x81, 0xfb, 0xf5, 0xfe,
	0xef, 0x15, 0xd3, 0xa2, 0xd8, 0xb5, 0xf4, 0xa1, 0xba, 0x00, 0xa6, 0x4e, 0x2e, 0x3a, 0x29, 0x9e,
	0xee, 0xf3, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xc8, 0x41, 0x1a, 0x92, 0x0b, 0x00, 0x00,
}
