// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flatsharing.proto

package v1 // import "src/flatsharing/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateHomeRequest struct {
	Home                 *Home    `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHomeRequest) Reset()         { *m = CreateHomeRequest{} }
func (m *CreateHomeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHomeRequest) ProtoMessage()    {}
func (*CreateHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_2c094713ff28c71e, []int{0}
}
func (m *CreateHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHomeRequest.Unmarshal(m, b)
}
func (m *CreateHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHomeRequest.Marshal(b, m, deterministic)
}
func (dst *CreateHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHomeRequest.Merge(dst, src)
}
func (m *CreateHomeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHomeRequest.Size(m)
}
func (m *CreateHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHomeRequest proto.InternalMessageInfo

func (m *CreateHomeRequest) GetHome() *Home {
	if m != nil {
		return m.Home
	}
	return nil
}

type CreateHomeResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHomeResponse) Reset()         { *m = CreateHomeResponse{} }
func (m *CreateHomeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateHomeResponse) ProtoMessage()    {}
func (*CreateHomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_2c094713ff28c71e, []int{1}
}
func (m *CreateHomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHomeResponse.Unmarshal(m, b)
}
func (m *CreateHomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHomeResponse.Marshal(b, m, deterministic)
}
func (dst *CreateHomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHomeResponse.Merge(dst, src)
}
func (m *CreateHomeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHomeResponse.Size(m)
}
func (m *CreateHomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHomeResponse proto.InternalMessageInfo

func (m *CreateHomeResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Home struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Home) Reset()         { *m = Home{} }
func (m *Home) String() string { return proto.CompactTextString(m) }
func (*Home) ProtoMessage()    {}
func (*Home) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_2c094713ff28c71e, []int{2}
}
func (m *Home) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Home.Unmarshal(m, b)
}
func (m *Home) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Home.Marshal(b, m, deterministic)
}
func (dst *Home) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Home.Merge(dst, src)
}
func (m *Home) XXX_Size() int {
	return xxx_messageInfo_Home.Size(m)
}
func (m *Home) XXX_DiscardUnknown() {
	xxx_messageInfo_Home.DiscardUnknown(m)
}

var xxx_messageInfo_Home proto.InternalMessageInfo

func (m *Home) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Home) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Home) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type CreatePurchaseRequest struct {
	Purchase             *Purchase `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePurchaseRequest) Reset()         { *m = CreatePurchaseRequest{} }
func (m *CreatePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePurchaseRequest) ProtoMessage()    {}
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_2c094713ff28c71e, []int{3}
}
func (m *CreatePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePurchaseRequest.Unmarshal(m, b)
}
func (m *CreatePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePurchaseRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePurchaseRequest.Merge(dst, src)
}
func (m *CreatePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePurchaseRequest.Size(m)
}
func (m *CreatePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePurchaseRequest proto.InternalMessageInfo

func (m *CreatePurchaseRequest) GetPurchase() *Purchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

type CreatePurchaseResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePurchaseResponse) Reset()         { *m = CreatePurchaseResponse{} }
func (m *CreatePurchaseResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePurchaseResponse) ProtoMessage()    {}
func (*CreatePurchaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_2c094713ff28c71e, []int{4}
}
func (m *CreatePurchaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePurchaseResponse.Unmarshal(m, b)
}
func (m *CreatePurchaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePurchaseResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePurchaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePurchaseResponse.Merge(dst, src)
}
func (m *CreatePurchaseResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePurchaseResponse.Size(m)
}
func (m *CreatePurchaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePurchaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePurchaseResponse proto.InternalMessageInfo

func (m *CreatePurchaseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Purchase struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeId               string   `protobuf:"bytes,2,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BuyerId              string   `protobuf:"bytes,4,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Shop                 string   `protobuf:"bytes,5,opt,name=shop,proto3" json:"shop,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc                 string   `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Purchase) Reset()         { *m = Purchase{} }
func (m *Purchase) String() string { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()    {}
func (*Purchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_flatsharing_2c094713ff28c71e, []int{5}
}
func (m *Purchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Purchase.Unmarshal(m, b)
}
func (m *Purchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Purchase.Marshal(b, m, deterministic)
}
func (dst *Purchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Purchase.Merge(dst, src)
}
func (m *Purchase) XXX_Size() int {
	return xxx_messageInfo_Purchase.Size(m)
}
func (m *Purchase) XXX_DiscardUnknown() {
	xxx_messageInfo_Purchase.DiscardUnknown(m)
}

var xxx_messageInfo_Purchase proto.InternalMessageInfo

func (m *Purchase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Purchase) GetHomeId() string {
	if m != nil {
		return m.HomeId
	}
	return ""
}

func (m *Purchase) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Purchase) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *Purchase) GetShop() string {
	if m != nil {
		return m.Shop
	}
	return ""
}

func (m *Purchase) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Purchase) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Purchase) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateHomeRequest)(nil), "flatsharing.v1.CreateHomeRequest")
	proto.RegisterType((*CreateHomeResponse)(nil), "flatsharing.v1.CreateHomeResponse")
	proto.RegisterType((*Home)(nil), "flatsharing.v1.Home")
	proto.RegisterType((*CreatePurchaseRequest)(nil), "flatsharing.v1.CreatePurchaseRequest")
	proto.RegisterType((*CreatePurchaseResponse)(nil), "flatsharing.v1.CreatePurchaseResponse")
	proto.RegisterType((*Purchase)(nil), "flatsharing.v1.Purchase")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HomeServicesClient is the client API for HomeServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HomeServicesClient interface {
	CreateHome(ctx context.Context, in *CreateHomeRequest, opts ...grpc.CallOption) (*CreateHomeResponse, error)
}

type homeServicesClient struct {
	cc *grpc.ClientConn
}

func NewHomeServicesClient(cc *grpc.ClientConn) HomeServicesClient {
	return &homeServicesClient{cc}
}

func (c *homeServicesClient) CreateHome(ctx context.Context, in *CreateHomeRequest, opts ...grpc.CallOption) (*CreateHomeResponse, error) {
	out := new(CreateHomeResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.HomeServices/CreateHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeServicesServer is the server API for HomeServices service.
type HomeServicesServer interface {
	CreateHome(context.Context, *CreateHomeRequest) (*CreateHomeResponse, error)
}

func RegisterHomeServicesServer(s *grpc.Server, srv HomeServicesServer) {
	s.RegisterService(&_HomeServices_serviceDesc, srv)
}

func _HomeServices_CreateHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServicesServer).CreateHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.HomeServices/CreateHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServicesServer).CreateHome(ctx, req.(*CreateHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HomeServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flatsharing.v1.HomeServices",
	HandlerType: (*HomeServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHome",
			Handler:    _HomeServices_CreateHome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flatsharing.proto",
}

// PurchaseServicesClient is the client API for PurchaseServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PurchaseServicesClient interface {
	CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error)
}

type purchaseServicesClient struct {
	cc *grpc.ClientConn
}

func NewPurchaseServicesClient(cc *grpc.ClientConn) PurchaseServicesClient {
	return &purchaseServicesClient{cc}
}

func (c *purchaseServicesClient) CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error) {
	out := new(CreatePurchaseResponse)
	err := c.cc.Invoke(ctx, "/flatsharing.v1.PurchaseServices/CreatePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseServicesServer is the server API for PurchaseServices service.
type PurchaseServicesServer interface {
	CreatePurchase(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error)
}

func RegisterPurchaseServicesServer(s *grpc.Server, srv PurchaseServicesServer) {
	s.RegisterService(&_PurchaseServices_serviceDesc, srv)
}

func _PurchaseServices_CreatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServicesServer).CreatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flatsharing.v1.PurchaseServices/CreatePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServicesServer).CreatePurchase(ctx, req.(*CreatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PurchaseServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flatsharing.v1.PurchaseServices",
	HandlerType: (*PurchaseServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePurchase",
			Handler:    _PurchaseServices_CreatePurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flatsharing.proto",
}

func init() { proto.RegisterFile("flatsharing.proto", fileDescriptor_flatsharing_2c094713ff28c71e) }

var fileDescriptor_flatsharing_2c094713ff28c71e = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0x42, 0x48, 0xd3, 0x61, 0xa9, 0xa8, 0x59, 0x76, 0x43, 0x00, 0x69, 0xb1, 0x00, 0x55,
	0x7b, 0x68, 0xd4, 0xc2, 0x69, 0x25, 0x0e, 0xc0, 0x85, 0x1c, 0x90, 0xd0, 0x72, 0xe3, 0x52, 0xb9,
	0x89, 0xdb, 0x58, 0x34, 0x71, 0x88, 0x9d, 0x68, 0xf7, 0xca, 0x99, 0x1b, 0xef, 0xc4, 0x0b, 0xf0,
	0x0a, 0x3c, 0x08, 0xb2, 0x9d, 0x86, 0xd6, 0xe5, 0xe7, 0x36, 0x33, 0xdf, 0x37, 0xe3, 0x6f, 0xbe,
	0x49, 0x60, 0xbc, 0xda, 0x10, 0x29, 0x72, 0x52, 0xb3, 0x72, 0x3d, 0xad, 0x6a, 0x2e, 0x39, 0x1a,
	0xed, 0x96, 0xda, 0x59, 0xf4, 0x60, 0xcd, 0xf9, 0x7a, 0x43, 0x63, 0x8d, 0x2e, 0x9b, 0x55, 0x4c,
	0x8b, 0x4a, 0x5e, 0x1b, 0x72, 0x74, 0x66, 0x83, 0x2b, 0x46, 0x37, 0xd9, 0xa2, 0x20, 0xe2, 0x53,
	0xc7, 0x78, 0xd8, 0x31, 0x48, 0xc5, 0x62, 0x52, 0x96, 0x5c, 0x12, 0xc9, 0x78, 0x29, 0x0c, 0x8a,
	0x5f, 0xc2, 0xf8, 0x4d, 0x4d, 0x89, 0xa4, 0x6f, 0x79, 0x41, 0x2f, 0xe9, 0xe7, 0x86, 0x0a, 0x89,
	0x26, 0xe0, 0xe5, 0xbc, 0xa0, 0xa1, 0x73, 0xe6, 0x4c, 0x6e, 0xcd, 0x8f, 0xa7, 0xfb, 0x82, 0xa6,
	0x9a, 0xaa, 0x19, 0xf8, 0x09, 0xa0, 0xdd, 0x76, 0x51, 0xf1, 0x52, 0x50, 0x34, 0x02, 0x97, 0x65,
	0xba, 0x7b, 0x78, 0xe9, 0xb2, 0x0c, 0x27, 0xe0, 0x29, 0xdc, 0xae, 0x23, 0x04, 0x5e, 0x49, 0x0a,
	0x1a, 0xba, 0xba, 0xa2, 0x63, 0xf4, 0x08, 0x20, 0xd5, 0x13, 0xb3, 0x05, 0x91, 0xe1, 0x50, 0x23,
	0xc3, 0xae, 0xf2, 0x4a, 0xe2, 0x77, 0x70, 0xcf, 0x3c, 0xf8, 0xbe, 0xa9, 0xd3, 0x9c, 0x88, 0x5e,
	0xf3, 0x0b, 0x08, 0xaa, 0xae, 0xd4, 0xe9, 0x0e, 0x6d, 0xdd, 0x7d, 0x4b, 0xcf, 0xc4, 0x13, 0x38,
	0xb1, 0xc7, 0xfd, 0x65, 0x87, 0xef, 0x0e, 0x04, 0x5b, 0xd2, 0xc1, 0x22, 0xa7, 0x30, 0x50, 0x76,
	0x2c, 0x58, 0xd6, 0xed, 0xe2, 0xab, 0x34, 0xd1, 0x40, 0x23, 0x68, 0xad, 0x80, 0x1b, 0x06, 0x50,
	0x69, 0x92, 0xa1, 0xfb, 0x10, 0x2c, 0x9b, 0x6b, 0x83, 0x78, 0x1a, 0x19, 0xe8, 0x3c, 0xd1, 0xae,
	0x88, 0x9c, 0x57, 0xe1, 0x4d, 0xe3, 0x8a, 0x8a, 0xd1, 0x09, 0xf8, 0xa4, 0xe0, 0x4d, 0x29, 0x43,
	0xdf, 0x8c, 0x31, 0x99, 0xe2, 0x66, 0x54, 0xa4, 0xe1, 0xc0, 0x70, 0x55, 0x6c, 0x39, 0x18, 0x58,
	0x0e, 0xce, 0xaf, 0xe0, 0x48, 0x1d, 0xe3, 0x03, 0xad, 0x5b, 0x96, 0x52, 0x81, 0x72, 0x80, 0xdf,
	0x27, 0x44, 0x8f, 0x6d, 0xd3, 0x0e, 0xbe, 0x8e, 0x08, 0xff, 0x8b, 0x62, 0xdc, 0xc3, 0x77, 0xbf,
	0xfc, 0xf8, 0xf9, 0xcd, 0xbd, 0x8d, 0x83, 0xb8, 0x9d, 0xc5, 0xca, 0x8b, 0x0b, 0xe7, 0x7c, 0xfe,
	0xd5, 0x81, 0x3b, 0x5b, 0x0b, 0xfb, 0xe7, 0xaf, 0x60, 0xb4, 0x7f, 0x01, 0xf4, 0xf4, 0xcf, 0xf3,
	0xad, 0x83, 0x47, 0xcf, 0xfe, 0x47, 0xeb, 0xa4, 0x9c, 0x6a, 0x29, 0x63, 0x7c, 0xa4, 0xa4, 0x6c,
	0x0f, 0x7f, 0xe1, 0x9c, 0xbf, 0x3e, 0xfe, 0x88, 0x44, 0x9d, 0xc6, 0x3b, 0x53, 0xe2, 0x76, 0xb6,
	0xf4, 0xf5, 0x7f, 0xf1, 0xfc, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x71, 0x92, 0xdf, 0x99,
	0x03, 0x00, 0x00,
}
